import { Type, Types } from "./types";
import { Rarity } from "./rarity";
import { Move, Moves } from "./moves";

export class Pokemon {
    public Petname: string | null = null;
    public Move: Move;
    public Atk: number;
    public Def: number;
    public Life: number;

    public constructor(
        public Id: number,
        public Name: string,
        public Types: Type[],
        public Rariry: Rarity = Rarity.Common,
        public Level: number = 1,
        public Stage: 1|2|3 = 1,
        public Evolves: number = 0,
        public Description: string = "The PokeDex doesn't have Data on this strange unknown Pokemon... Have you maybe found a new type of Pokemon?",
        public TradeEvolve: boolean = false,
        public UsesStone: boolean = false,
        public BaseAtk: number = 40,
        public BaseDef: number = 40,
        public BaseLife: number = 40,
        public availableMoves: Move[] = [Moves.Scratch, Moves.Pound]
    ) {
        this.Move = this.availableMoves[Math.floor(Math.random() * this.availableMoves.length)];
        // leaving this in here becuase of editor beeing racist and not recognizing the function does this shit...
        this.Atk = BaseAtk;
        this.Def = BaseDef;
        this.Life = BaseLife;
        // end racist crap
        
        this.updateStats();
    }

    public Attack(foe: Pokemon): number {
        let precalc;

        if (this.Move.Power === null) {
            precalc = (((((2*this.Level)/5)+2) * this.Atk / foe.Def)/50) + 2;
        } else {
            precalc = (((((2*this.Level)/5)+2) * this.Move.Power! * this.Atk / foe.Def)/50) + 2;
        }

        const random = Math.floor(Math.random()*(100-85+1)+85) / 100;

        let sameType = 1;
        let typeEffective = 1;

        let nullified = false;

        if (this.Types.some( type2 => type2.Id === this.Move.Type.Id)) {
            sameType = 1.5;
        }

        foe.Types.forEach(foeType => {
            let _nullified = false;

            foeType.Weakness.forEach(weak => {
                if (weak.Id === this.Move.Type.Id) {
                    typeEffective += 1;
                }
            });

            foeType.Strength.forEach(strength => {
                if (strength.Id === this.Move.Type.Id) {
                    typeEffective -= 0.25
                }
            });

            foeType.Nullifies.forEach(nullifies => {
                if (nullifies.Id === this.Move.Type.Id) {
                    nullified = true;
                }
            });

            if (_nullified && foe.Types.length === 1) {
                nullified = true;
            }
        });

        if (nullified) {
            return foe.Life;
        }

        const modifier = sameType * typeEffective * random;

        const damage = precalc * modifier;

        foe.Life = Math.round(foe.Life - damage);
        return foe.Life;
    }

    public updateStats() {
        this.Life = Math.round(this.BaseLife * 2 * this.Level / 100 + 10 + this.Level);
        this.Atk = Math.round(this.BaseAtk * 2 * this.Level / 100 + 5);
        this.Def = Math.round(this.BaseDef * 2 * this.Level / 100 + 5);
    }

    public LvlUp(numberOfLevels: number): number {
        if (this.Level <100) {
            if ((this.Level + numberOfLevels) < 100) {
                this.Level += numberOfLevels;
            } else {
                this.Level = 100;
            }
        }
        
        this.updateStats();
        return this.Level;
    }

    public Clone(): Pokemon {
        const pkmn = new Pokemon(this.Id, this.Name, this.Types, this.Rariry, this.Level, this.Stage, this.Evolves, this.Description, this.TradeEvolve, this.UsesStone, this.BaseAtk, this.BaseDef, this.BaseLife, this.availableMoves);
        pkmn.Petname = this.Petname;
        return pkmn;
    }
}
// change to array of raw data and initialize only needed stuff.. why the heck did I even do this? :S
//... same for the moves.. guess only the types remain so.. gotta think about a way to identify everything but should work well :)
const InternPokemon = [
    new Pokemon(0, "MissingNo.", [Types.Normal], Rarity.Unobtainable, 1, 1, 0, "コメント さくせいちゅう", false, false),
    new Pokemon(1, "Bulbasaur", [Types.Grass,Types.Poison,], Rarity.Common, 1, 1, 16, "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.", false, false, 49, 49, 45, [Moves.Tackle,Moves.Growl,Moves.LeechSeed,Moves.VineWhip,Moves.PoisonPowder,Moves.SleepPowder,Moves.TakeDown,Moves.RazorLeaf,Moves.SweetScent,Moves.Growth,Moves.DoubleEdge,Moves.WorrySeed,Moves.Synthesis,Moves.SeedBomb,Moves.Amnesia,Moves.Charm,Moves.Curse,Moves.Endure,Moves.GigaDrain,Moves.GrassWhistle,Moves.GrassyTerrain,Moves.Ingrain,Moves.LeafStorm,Moves.MagicalLeaf,Moves.NaturePower,Moves.PetalDance,Moves.PowerWhip,Moves.SkullBash,Moves.Sludge,]), // Pkmn #001
    new Pokemon(2, "Ivysaur", [Types.Grass,Types.Poison,], Rarity.Uncommon, 1, 2, 32, "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", false, false, 62, 63, 60, [Moves.Tackle,Moves.Growl,Moves.LeechSeed,Moves.Growl,Moves.LeechSeed,Moves.VineWhip,Moves.PoisonPowder,Moves.SleepPowder,Moves.TakeDown,Moves.RazorLeaf,Moves.SweetScent,Moves.Growth,Moves.DoubleEdge,Moves.WorrySeed,Moves.Synthesis,Moves.SolarBeam,Moves.Amnesia,Moves.Charm,Moves.Curse,Moves.Endure,Moves.GigaDrain,Moves.GrassWhistle,Moves.GrassyTerrain,Moves.Ingrain,Moves.LeafStorm,Moves.MagicalLeaf,Moves.NaturePower,Moves.PetalDance,Moves.PowerWhip,Moves.SkullBash,Moves.Sludge,]), // Pkmn #002
    new Pokemon(3, "Venusaur", [Types.Grass,Types.Poison,], Rarity.Rare, 1, 3, 0, "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.", false, false, 82, 83, 80, [Moves.Tackle,Moves.Growl,Moves.LeechSeed,Moves.VineWhip,Moves.Growl,Moves.LeechSeed,Moves.VineWhip,Moves.PoisonPowder,Moves.SleepPowder,Moves.TakeDown,Moves.RazorLeaf,Moves.SweetScent,Moves.Growth,Moves.DoubleEdge,Moves.PetalDance,Moves.WorrySeed,Moves.Synthesis,Moves.PetalBlizzard,Moves.SolarBeam,Moves.Amnesia,Moves.Charm,Moves.Curse,Moves.Endure,Moves.GigaDrain,Moves.GrassWhistle,Moves.GrassyTerrain,Moves.Ingrain,Moves.LeafStorm,Moves.MagicalLeaf,Moves.NaturePower,Moves.PetalDance,Moves.PowerWhip,Moves.SkullBash,Moves.Sludge,]), // Pkmn #003
    new Pokemon(4, "Charmander", [Types.Fire,], Rarity.Common, 1, 1, 16, "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.", false, false, 52, 43, 39, [Moves.Scratch,Moves.Growl,Moves.Ember,Moves.Smokescreen,Moves.DragonRage,Moves.ScaryFace,Moves.FireFang,Moves.FlameBurst,Moves.Slash,Moves.Flamethrower,Moves.FireSpin,Moves.Inferno,Moves.AirCutter,Moves.AncientPower,Moves.BeatUp,Moves.BellyDrum,Moves.Bite,Moves.Counter,Moves.Crunch,Moves.DragonDance,Moves.DragonPulse,Moves.DragonRush,Moves.FlareBlitz,Moves.FocusPunch,Moves.MetalClaw,Moves.Outrage,]), // Pkmn #004
    new Pokemon(5, "Charmeleon", [Types.Fire,], Rarity.Uncommon, 1, 2, 36, "When it swings its burning tail, it elevates the temperature to unbearably high levels.", false, false, 64, 58, 58, [Moves.Scratch,Moves.Growl,Moves.Ember,Moves.Ember,Moves.Smokescreen,Moves.DragonRage,Moves.ScaryFace,Moves.FireFang,Moves.FlameBurst,Moves.Slash,Moves.Flamethrower,Moves.FireSpin,Moves.Inferno,Moves.AirCutter,Moves.AncientPower,Moves.BeatUp,Moves.BellyDrum,Moves.Bite,Moves.Counter,Moves.Crunch,Moves.DragonDance,Moves.DragonPulse,Moves.DragonRush,Moves.FlareBlitz,Moves.FocusPunch,Moves.MetalClaw,Moves.Outrage,]), // Pkmn #005
    new Pokemon(6, "Charizard", [Types.Fire,Types.Flying,], Rarity.Rare, 1, 3, 0, "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.", false, false, 84, 78, 78, [Moves.FlareBlitz,Moves.HeatWave,Moves.DragonClaw,Moves.ShadowClaw,Moves.AirSlash,Moves.Scratch,Moves.Growl,Moves.Ember,Moves.Smokescreen,Moves.Ember,Moves.Smokescreen,Moves.DragonRage,Moves.ScaryFace,Moves.FireFang,Moves.FlameBurst,Moves.WingAttack,Moves.Slash,Moves.Flamethrower,Moves.FireSpin,Moves.Inferno,Moves.HeatWave,Moves.FlareBlitz,Moves.AirCutter,Moves.AncientPower,Moves.BeatUp,Moves.BellyDrum,Moves.Bite,Moves.Counter,Moves.Crunch,Moves.DragonDance,Moves.DragonPulse,Moves.DragonRush,Moves.FlareBlitz,Moves.FocusPunch,Moves.MetalClaw,Moves.Outrage,]), // Pkmn #006
    new Pokemon(7, "Squirtle", [Types.Water,], Rarity.Common, 1, 1, 16, "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.", false, false, 48, 65, 44, [Moves.Tackle,Moves.TailWhip,Moves.WaterGun,Moves.Withdraw,Moves.Bubble,Moves.Bite,Moves.RapidSpin,Moves.Protect,Moves.WaterPulse,Moves.AquaTail,Moves.SkullBash,Moves.IronDefense,Moves.RainDance,Moves.HydroPump,Moves.AquaJet,Moves.AquaRing,Moves.AuraSphere,Moves.Brine,Moves.DragonPulse,Moves.FakeOut,Moves.Flail,Moves.Foresight,Moves.Haze,Moves.MirrorCoat,Moves.Mist,Moves.MudSport,Moves.MuddyWater,Moves.Refresh,Moves.WaterSpout,Moves.Yawn,]), // Pkmn #007
    new Pokemon(8, "Wartortle", [Types.Water,], Rarity.Uncommon, 1, 2, 36, "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.", false, false, 63, 80, 59, [Moves.Tackle,Moves.TailWhip,Moves.Bubble,Moves.TailWhip,Moves.WaterGun,Moves.Withdraw,Moves.Bubble,Moves.Bite,Moves.RapidSpin,Moves.Protect,Moves.WaterPulse,Moves.AquaTail,Moves.SkullBash,Moves.IronDefense,Moves.RainDance,Moves.HydroPump,Moves.AquaJet,Moves.AquaRing,Moves.AuraSphere,Moves.Brine,Moves.DragonPulse,Moves.FakeOut,Moves.Flail,Moves.Foresight,Moves.Haze,Moves.MirrorCoat,Moves.Mist,Moves.MudSport,Moves.MuddyWater,Moves.Refresh,Moves.WaterSpout,Moves.Yawn,]), // Pkmn #008
    new Pokemon(9, "Blastoise", [Types.Water,], Rarity.Rare, 1, 3, 0, "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.", false, false, 83, 100, 79, [Moves.FlashCannon,Moves.Tackle,Moves.TailWhip,Moves.Bubble,Moves.Withdraw,Moves.TailWhip,Moves.WaterGun,Moves.Withdraw,Moves.Bubble,Moves.Bite,Moves.RapidSpin,Moves.Protect,Moves.WaterPulse,Moves.AquaTail,Moves.SkullBash,Moves.IronDefense,Moves.RainDance,Moves.HydroPump,Moves.AquaJet,Moves.AquaRing,Moves.AuraSphere,Moves.Brine,Moves.DragonPulse,Moves.FakeOut,Moves.Flail,Moves.Foresight,Moves.Haze,Moves.MirrorCoat,Moves.Mist,Moves.MudSport,Moves.MuddyWater,Moves.Refresh,Moves.WaterSpout,Moves.Yawn,]), // Pkmn #009
    new Pokemon(10, "Caterpie", [Types.Bug,], Rarity.Common, 1, 1, 7, "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.", false, false, 30, 35, 45, [Moves.Tackle,Moves.StringShot,Moves.BugBite,]), // Pkmn #010
    new Pokemon(11, "Metapod", [Types.Bug,], Rarity.Uncommon, 1, 2, 10, "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.", false, false, 20, 55, 50, [Moves.Harden,Moves.Harden,]), // Pkmn #011
    new Pokemon(12, "Butterfree", [Types.Bug,Types.Flying,], Rarity.Rare, 1, 3, 0, "In battle, it flaps its wings at high speed to release highly toxic dust into the air.", false, false, 45, 50, 60, [Moves.Confusion,Moves.Confusion,Moves.PoisonPowder,Moves.StunSpore,Moves.SleepPowder,Moves.Gust,Moves.Supersonic,Moves.Whirlwind,Moves.Psybeam,Moves.SilverWind,Moves.Tailwind,Moves.RagePowder,Moves.Safeguard,Moves.Captivate,Moves.BugBuzz,Moves.QuiverDance,]), // Pkmn #012
    new Pokemon(13, "Weedle", [Types.Bug,Types.Poison,], Rarity.Common, 1, 1, 7, "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.", false, false, 35, 30, 40, [Moves.PoisonSting,Moves.StringShot,Moves.BugBite,]), // Pkmn #013
    new Pokemon(14, "Kakuna", [Types.Bug,Types.Poison,], Rarity.Uncommon, 1, 2, 10, "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.", false, false, 25, 50, 45, [Moves.Harden,Moves.Harden,]), // Pkmn #014
    new Pokemon(15, "Beedrill", [Types.Bug,Types.Poison,], Rarity.Rare, 1, 3, 0, "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.", false, false, 90, 40, 65, [Moves.FuryAttack,Moves.FuryAttack,Moves.FocusEnergy,Moves.Twineedle,Moves.Rage,Moves.Pursuit,Moves.ToxicSpikes,Moves.PinMissile,Moves.Agility,Moves.Assurance,Moves.PoisonJab,Moves.Endeavor,Moves.FellStinger,]), // Pkmn #015
    new Pokemon(16, "Pidgey", [Types.Normal,Types.Flying,], Rarity.Common, 1, 1, 18, "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.", false, false, 45, 40, 40, [Moves.Tackle,Moves.SandAttack,Moves.Gust,Moves.QuickAttack,Moves.Whirlwind,Moves.Twister,Moves.FeatherDance,Moves.Agility,Moves.WingAttack,Moves.Roost,Moves.Tailwind,Moves.MirrorMove,Moves.AirSlash,Moves.Hurricane,Moves.AirCutter,Moves.AirSlash,Moves.BraveBird,Moves.Defog,Moves.FeintAttack,Moves.Foresight,Moves.Pursuit,Moves.SteelWing,Moves.Uproar,]), // Pkmn #016
    new Pokemon(17, "Pidgeotto", [Types.Normal,Types.Flying,], Rarity.Uncommon, 1, 2, 36, "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.", false, false, 60, 55, 63, [Moves.Tackle,Moves.SandAttack,Moves.Gust,Moves.SandAttack,Moves.Gust,Moves.QuickAttack,Moves.Whirlwind,Moves.Twister,Moves.FeatherDance,Moves.Agility,Moves.WingAttack,Moves.Roost,Moves.Tailwind,Moves.MirrorMove,Moves.AirSlash,Moves.Hurricane,Moves.AirCutter,Moves.AirSlash,Moves.BraveBird,Moves.Defog,Moves.FeintAttack,Moves.Foresight,Moves.Pursuit,Moves.SteelWing,Moves.Uproar,]), // Pkmn #017
    new Pokemon(18, "Pidgeot", [Types.Normal,Types.Flying,], Rarity.Rare, 1, 3, 0, "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.", false, false, 80, 75, 83, [Moves.Hurricane,Moves.Tackle,Moves.SandAttack,Moves.Gust,Moves.QuickAttack,Moves.SandAttack,Moves.Gust,Moves.QuickAttack,Moves.Whirlwind,Moves.Twister,Moves.FeatherDance,Moves.Agility,Moves.WingAttack,Moves.Roost,Moves.Tailwind,Moves.MirrorMove,Moves.AirSlash,Moves.Hurricane,Moves.AirCutter,Moves.AirSlash,Moves.BraveBird,Moves.Defog,Moves.FeintAttack,Moves.Foresight,Moves.Pursuit,Moves.SteelWing,Moves.Uproar,]), // Pkmn #018
    new Pokemon(19, "Rattata", [Types.Normal,], Rarity.Common, 1, 1, 20, "Bites anything when it attacks. Small and very quick, it is a common sight in many places.", false, false, 56, 35, 30,), // Pkmn #019
    new Pokemon(20, "Raticate", [Types.Normal,], Rarity.Uncommon, 1, 2, 0, "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.", false, false, 81, 60, 55), // Pkmn #020
    new Pokemon(21, "Spearow", [Types.Normal,Types.Flying,], Rarity.Common, 1, 1, 20, "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.", false, false, 60, 30, 40, [Moves.Peck,Moves.Growl,Moves.Leer,Moves.FuryAttack,Moves.Pursuit,Moves.AerialAce,Moves.MirrorMove,Moves.Agility,Moves.Assurance,Moves.Roost,Moves.DrillPeck,Moves.Astonish,Moves.FeatherDance,Moves.FeintAttack,Moves.QuickAttack,Moves.RazorWind,Moves.ScaryFace,Moves.SkyAttack,Moves.SteelWing,Moves.TriAttack,Moves.Uproar,Moves.Whirlwind,]), // Pkmn #021
    new Pokemon(22, "Fearow", [Types.Normal,Types.Flying,], Rarity.Uncommon, 1, 2, 0, "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.", false, false, 90, 65, 65, [Moves.DrillRun,Moves.Pluck,Moves.Peck,Moves.Growl,Moves.Leer,Moves.FuryAttack,Moves.Leer,Moves.FuryAttack,Moves.Pursuit,Moves.AerialAce,Moves.MirrorMove,Moves.Agility,Moves.Assurance,Moves.Roost,Moves.DrillPeck,Moves.DrillRun,Moves.Astonish,Moves.FeatherDance,Moves.FeintAttack,Moves.QuickAttack,Moves.RazorWind,Moves.ScaryFace,Moves.SkyAttack,Moves.SteelWing,Moves.TriAttack,Moves.Uproar,Moves.Whirlwind,]), // Pkmn #022
    new Pokemon(23, "Ekans", [Types.Poison,], Rarity.Common, 1, 1, 22, "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.", false, false, 60, 44, 35, [Moves.Wrap,Moves.Leer,Moves.PoisonSting,Moves.Bite,Moves.Glare,Moves.Screech,Moves.Acid,Moves.Stockpile,Moves.Swallow,Moves.SpitUp,Moves.AcidSpray,Moves.MudBomb,Moves.GastroAcid,Moves.Belch,Moves.Haze,Moves.Coil,Moves.GunkShot,Moves.BeatUp,Moves.Disable,Moves.IronTail,Moves.PoisonFang,Moves.PoisonTail,Moves.Pursuit,Moves.ScaryFace,Moves.Slam,Moves.Snatch,Moves.Spite,Moves.SuckerPunch,Moves.Switcheroo,]), // Pkmn #023
    new Pokemon(24, "Arbok", [Types.Poison,], Rarity.Uncommon, 1, 2, 0, "It is rumored that the ferocious warning markings on its belly differ from area to area.", false, false, 85, 69, 60, [Moves.IceFang,Moves.ThunderFang,Moves.FireFang,Moves.Wrap,Moves.Leer,Moves.PoisonSting,Moves.Bite,Moves.PoisonSting,Moves.Bite,Moves.Glare,Moves.Screech,Moves.Acid,Moves.Crunch,Moves.Stockpile,Moves.Swallow,Moves.SpitUp,Moves.AcidSpray,Moves.MudBomb,Moves.GastroAcid,Moves.Belch,Moves.Haze,Moves.Coil,Moves.GunkShot,Moves.BeatUp,Moves.Disable,Moves.IronTail,Moves.PoisonFang,Moves.PoisonTail,Moves.Pursuit,Moves.ScaryFace,Moves.Slam,Moves.Snatch,Moves.Spite,Moves.SuckerPunch,Moves.Switcheroo,]), // Pkmn #024
    new Pokemon(25, "Pikachu", [Types.Electric,], Rarity.Common, 1, 1, 0, "When several of these Pokémon gather, their electricity could build and cause lightning storms.", false, true, 55, 40, 35, [Moves.TailWhip,Moves.ThunderShock,Moves.Growl,Moves.PlayNice,Moves.QuickAttack,Moves.ThunderWave,Moves.ElectroBall,Moves.DoubleTeam,Moves.Nuzzle,Moves.Slam,Moves.Thunderbolt,Moves.Feint,Moves.Agility,Moves.Discharge,Moves.LightScreen,Moves.Thunder,Moves.Bestow,Moves.Bide,Moves.Charge,Moves.DisarmingVoice,Moves.DoubleSlap,Moves.Encore,Moves.Endure,Moves.FakeOut,Moves.Flail,Moves.LuckyChant,Moves.Present,Moves.Reversal,Moves.ThunderPunch,Moves.Tickle,Moves.Wish,Moves.VoltTackle,]), // Pkmn #025
    new Pokemon(26, "Raichu", [Types.Electric,], Rarity.Rare, 1, 2, 0, "Its long tail serves as a ground to protect itself from its own high voltage power.", false, false, 90, 55, 60, [Moves.ThunderShock,Moves.TailWhip,Moves.QuickAttack,Moves.Thunderbolt,Moves.Bestow,Moves.Bide,Moves.Charge,Moves.DisarmingVoice,Moves.DoubleSlap,Moves.Encore,Moves.Endure,Moves.FakeOut,Moves.Flail,Moves.LuckyChant,Moves.Present,Moves.Reversal,Moves.ThunderPunch,Moves.Tickle,Moves.Wish,Moves.VoltTackle,]), // Pkmn #026
    new Pokemon(27, "Sandshrew", [Types.Ground,], Rarity.Common, 1, 1, 22, "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.", false, false, 75, 85, 50, [Moves.Scratch,Moves.DefenseCurl,Moves.SandAttack,Moves.PoisonSting,Moves.Rollout,Moves.RapidSpin,Moves.Swift,Moves.FuryCutter,Moves.Magnitude,Moves.FurySwipes,Moves.SandTomb,Moves.Slash,Moves.Dig,Moves.GyroBall,Moves.SwordsDance,Moves.Sandstorm,Moves.Earthquake,Moves.ChipAway,Moves.Counter,Moves.CrushClaw,Moves.Endure,Moves.Flail,Moves.MetalClaw,Moves.MudShot,Moves.NightSlash,Moves.RapidSpin,Moves.RockClimb,Moves.Rototiller,]), // Pkmn #027
    new Pokemon(28, "Sandslash", [Types.Ground,], Rarity.Uncommon, 1, 2, 0, "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.", false, false, 100, 110, 75, [Moves.Scratch,Moves.DefenseCurl,Moves.SandAttack,Moves.PoisonSting,Moves.SandAttack,Moves.PoisonSting,Moves.Rollout,Moves.RapidSpin,Moves.Swift,Moves.FuryCutter,Moves.Magnitude,Moves.FurySwipes,Moves.CrushClaw,Moves.SandTomb,Moves.Slash,Moves.Dig,Moves.GyroBall,Moves.SwordsDance,Moves.Sandstorm,Moves.Earthquake,Moves.ChipAway,Moves.Counter,Moves.CrushClaw,Moves.Endure,Moves.Flail,Moves.MetalClaw,Moves.MudShot,Moves.NightSlash,Moves.RapidSpin,Moves.RockClimb,Moves.Rototiller,]), // Pkmn #028
    new Pokemon(29, "Nidoran♀", [Types.Poison,], Rarity.Common, 1, 1, 16, "Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.", false, false, 47, 52, 55, [Moves.Growl,Moves.Scratch,Moves.TailWhip,Moves.DoubleKick,Moves.PoisonSting,Moves.FurySwipes,Moves.Bite,Moves.HelpingHand,Moves.ToxicSpikes,Moves.Flatter,Moves.Crunch,Moves.Captivate,Moves.PoisonFang,Moves.BeatUp,Moves.Charm,Moves.ChipAway,Moves.Counter,Moves.Disable,Moves.Endure,Moves.FocusEnergy,Moves.IronTail,Moves.PoisonTail,Moves.Pursuit,Moves.SkullBash,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #029
    new Pokemon(30, "Nidorina", [Types.Poison,], Rarity.Uncommon, 1, 2, 0, "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.", false, true, 62, 67, 70, [Moves.Growl,Moves.Scratch,Moves.TailWhip,Moves.DoubleKick,Moves.PoisonSting,Moves.FurySwipes,Moves.Bite,Moves.HelpingHand,Moves.ToxicSpikes,Moves.Flatter,Moves.Crunch,Moves.Captivate,Moves.PoisonFang,Moves.BeatUp,Moves.Charm,Moves.ChipAway,Moves.Counter,Moves.Disable,Moves.Endure,Moves.FocusEnergy,Moves.IronTail,Moves.PoisonTail,Moves.Pursuit,Moves.SkullBash,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #030
    new Pokemon(31, "Nidoqueen", [Types.Poison,Types.Ground,], Rarity.Rare, 1, 3, 0, "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.", false, false, 92, 87, 90, [Moves.Superpower,Moves.Scratch,Moves.TailWhip,Moves.DoubleKick,Moves.PoisonSting,Moves.ChipAway,Moves.BodySlam,Moves.EarthPower,Moves.Superpower,Moves.BeatUp,Moves.Charm,Moves.ChipAway,Moves.Counter,Moves.Disable,Moves.Endure,Moves.FocusEnergy,Moves.IronTail,Moves.PoisonTail,Moves.Pursuit,Moves.SkullBash,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #031
    new Pokemon(32, "Nidoran♂", [Types.Poison,], Rarity.Common, 1, 1, 16, "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.", false, false, 57, 40, 46, [Moves.Leer,Moves.Peck,Moves.FocusEnergy,Moves.DoubleKick,Moves.PoisonSting,Moves.FuryAttack,Moves.HornAttack,Moves.HelpingHand,Moves.ToxicSpikes,Moves.Flatter,Moves.PoisonJab,Moves.Captivate,Moves.HornDrill,Moves.Amnesia,Moves.BeatUp,Moves.ChipAway,Moves.Confusion,Moves.Counter,Moves.Disable,Moves.Endure,Moves.HeadSmash,Moves.IronTail,Moves.PoisonTail,Moves.SuckerPunch,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #032
    new Pokemon(33, "Nidorino", [Types.Poison,], Rarity.Uncommon, 1, 2, 0, "An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.", false, false, 72, 57, 61, [Moves.Leer,Moves.Peck,Moves.FocusEnergy,Moves.DoubleKick,Moves.PoisonSting,Moves.FuryAttack,Moves.HornAttack,Moves.HelpingHand,Moves.ToxicSpikes,Moves.Flatter,Moves.PoisonJab,Moves.Captivate,Moves.HornDrill,Moves.Amnesia,Moves.BeatUp,Moves.ChipAway,Moves.Confusion,Moves.Counter,Moves.Disable,Moves.Endure,Moves.HeadSmash,Moves.IronTail,Moves.PoisonTail,Moves.SuckerPunch,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #033
    new Pokemon(34, "Nidoking", [Types.Poison,Types.Ground,], Rarity.Rare, 1, 3, 0, "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.", false, false, 102, 77, 81, [Moves.Megahorn,Moves.Peck,Moves.FocusEnergy,Moves.DoubleKick,Moves.PoisonSting,Moves.ChipAway,Moves.Thrash,Moves.EarthPower,Moves.Megahorn,Moves.Amnesia,Moves.BeatUp,Moves.ChipAway,Moves.Confusion,Moves.Counter,Moves.Disable,Moves.Endure,Moves.HeadSmash,Moves.IronTail,Moves.PoisonTail,Moves.SuckerPunch,Moves.Supersonic,Moves.TakeDown,Moves.VenomDrench,]), // Pkmn #034
    new Pokemon(35, "Clefairy", [Types.Fairy,], Rarity.Uncommon, 1, 1, 0, "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.", false, true, 45, 48, 70, [Moves.AfterYou,Moves.HealingWish,Moves.DisarmingVoice,Moves.Pound,Moves.Growl,Moves.Encore,Moves.Sing,Moves.DoubleSlap,Moves.DefenseCurl,Moves.FollowMe,Moves.Bestow,Moves.WakeUpSlap,Moves.Minimize,Moves.StoredPower,Moves.Metronome,Moves.CosmicPower,Moves.LuckyChant,Moves.BodySlam,Moves.Moonlight,Moves.Moonblast,Moves.Gravity,Moves.MeteorMash,Moves.HealingWish,Moves.AfterYou,Moves.Amnesia,Moves.Aromatherapy,Moves.BellyDrum,Moves.Covet,Moves.FakeTears,Moves.HealPulse,Moves.Metronome,Moves.Mimic,Moves.MistyTerrain,Moves.Present,Moves.Splash,Moves.StoredPower,Moves.Tickle,Moves.Wish,]), // Pkmn #035
    new Pokemon(36, "Clefable", [Types.Fairy,], Rarity.Rare, 1, 2, 0, "A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.", false, false, 70, 73, 95, [Moves.DisarmingVoice,Moves.Sing,Moves.DoubleSlap,Moves.Minimize,Moves.Metronome,Moves.Amnesia,Moves.Aromatherapy,Moves.BellyDrum,Moves.Covet,Moves.FakeTears,Moves.HealPulse,Moves.Metronome,Moves.Mimic,Moves.MistyTerrain,Moves.Present,Moves.Splash,Moves.StoredPower,Moves.Tickle,Moves.Wish,]), // Pkmn #036
    new Pokemon(37, "Vulpix", [Types.Fire,], Rarity.Uncommon, 1, 1, 0, "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.", false, true, 41, 40, 38, [Moves.Ember,Moves.TailWhip,Moves.Roar,Moves.BabyDollEyes,Moves.QuickAttack,Moves.FireSpin,Moves.ConfuseRay,Moves.Imprison,Moves.FeintAttack,Moves.FlameBurst,Moves.WillOWisp,Moves.Hex,Moves.Payback,Moves.Flamethrower,Moves.Safeguard,Moves.Extrasensory,Moves.FireBlast,Moves.Grudge,Moves.Captivate,Moves.Inferno,Moves.Captivate,Moves.Disable,Moves.Extrasensory,Moves.FeintAttack,Moves.Flail,Moves.FlareBlitz,Moves.HeatWave,Moves.Hex,Moves.Howl,Moves.Hypnosis,Moves.PowerSwap,Moves.SecretPower,Moves.Spite,Moves.TailSlap,]), // Pkmn #037
    new Pokemon(38, "Ninetales", [Types.Fire,], Rarity.Rare, 1, 2, 0, "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.", false, false, 76, 75, 73, [Moves.Imprison,Moves.NastyPlot,Moves.Flamethrower,Moves.QuickAttack,Moves.ConfuseRay,Moves.Safeguard,Moves.Captivate,Moves.Disable,Moves.Extrasensory,Moves.FeintAttack,Moves.Flail,Moves.FlareBlitz,Moves.HeatWave,Moves.Hex,Moves.Howl,Moves.Hypnosis,Moves.PowerSwap,Moves.SecretPower,Moves.Spite,Moves.TailSlap,]), // Pkmn #038
    new Pokemon(39, "Jigglypuff", [Types.Normal,Types.Fairy,], Rarity.Common, 1, 1, 0, "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.", false, true, 45, 20, 115, [Moves.Sing,Moves.DefenseCurl,Moves.Pound,Moves.PlayNice,Moves.Disable,Moves.Round,Moves.Rollout,Moves.DoubleSlap,Moves.Rest,Moves.BodySlam,Moves.GyroBall,Moves.WakeUpSlap,Moves.Mimic,Moves.HyperVoice,Moves.DisarmingVoice,Moves.DoubleEdge,Moves.Captivate,Moves.Covet,Moves.FakeTears,Moves.FeintAttack,Moves.Gravity,Moves.HealPulse,Moves.LastResort,Moves.MistyTerrain,Moves.PerishSong,Moves.Present,Moves.Punishment,Moves.SleepTalk,Moves.Wish,]), // Pkmn #039
    new Pokemon(40, "Wigglytuff", [Types.Normal,Types.Fairy,], Rarity.Rare, 1, 2, 0, "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.", false, false, 70, 45, 140, [Moves.DoubleEdge,Moves.PlayRough,Moves.Sing,Moves.Disable,Moves.DefenseCurl,Moves.DoubleSlap,Moves.Captivate,Moves.Covet,Moves.FakeTears,Moves.FeintAttack,Moves.Gravity,Moves.HealPulse,Moves.LastResort,Moves.MistyTerrain,Moves.PerishSong,Moves.Present,Moves.Punishment,Moves.SleepTalk,Moves.Wish,]), // Pkmn #040
    new Pokemon(41, "Zubat", [Types.Poison,Types.Flying,], Rarity.Common, 1, 1, 22, "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.", false, false, 45, 35, 40, [Moves.LeechLife,Moves.Supersonic,Moves.Astonish,Moves.Bite,Moves.WingAttack,Moves.ConfuseRay,Moves.Swift,Moves.AirCutter,Moves.Acrobatics,Moves.MeanLook,Moves.PoisonFang,Moves.Haze,Moves.AirSlash,Moves.BraveBird,Moves.Curse,Moves.Defog,Moves.FeintAttack,Moves.GigaDrain,Moves.Gust,Moves.Hypnosis,Moves.NastyPlot,Moves.Pursuit,Moves.QuickAttack,Moves.SteelWing,Moves.VenomDrench,Moves.Whirlwind,Moves.ZenHeadbutt,]), // Pkmn #041
    new Pokemon(42, "Golbat", [Types.Poison,Types.Flying,], Rarity.Uncommon, 1, 2, 0, "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.", false, false, 80, 70, 75, [Moves.Screech,Moves.LeechLife,Moves.Supersonic,Moves.Astonish,Moves.Supersonic,Moves.Astonish,Moves.Bite,Moves.WingAttack,Moves.ConfuseRay,Moves.Swift,Moves.AirCutter,Moves.Acrobatics,Moves.MeanLook,Moves.PoisonFang,Moves.Haze,Moves.AirSlash,Moves.BraveBird,Moves.Curse,Moves.Defog,Moves.FeintAttack,Moves.GigaDrain,Moves.Gust,Moves.Hypnosis,Moves.NastyPlot,Moves.Pursuit,Moves.QuickAttack,Moves.SteelWing,Moves.VenomDrench,Moves.Whirlwind,Moves.ZenHeadbutt,]), // Pkmn #042
    new Pokemon(43, "Oddish", [Types.Grass,Types.Poison,], Rarity.Common, 1, 1, 21, "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.", false, false, 50, 55, 45, [Moves.Absorb,Moves.SweetScent,Moves.Acid,Moves.PoisonPowder,Moves.StunSpore,Moves.SleepPowder,Moves.MegaDrain,Moves.LuckyChant,Moves.NaturalGift,Moves.Moonlight,Moves.GigaDrain,Moves.PetalDance,Moves.GrassyTerrain,Moves.AfterYou,Moves.Charm,Moves.Flail,Moves.Ingrain,Moves.NaturePower,Moves.RazorLeaf,Moves.SecretPower,Moves.Synthesis,Moves.TeeterDance,Moves.Tickle,]), // Pkmn #043
    new Pokemon(44, "Gloom", [Types.Grass,Types.Poison,], Rarity.Uncommon, 1, 2, 0, "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.", false, true, 65, 70, 60, [Moves.Absorb,Moves.SweetScent,Moves.Acid,Moves.SweetScent,Moves.Acid,Moves.PoisonPowder,Moves.StunSpore,Moves.SleepPowder,Moves.MegaDrain,Moves.LuckyChant,Moves.NaturalGift,Moves.Moonlight,Moves.GigaDrain,Moves.PetalBlizzard,Moves.PetalDance,Moves.GrassyTerrain,Moves.AfterYou,Moves.Charm,Moves.Flail,Moves.Ingrain,Moves.NaturePower,Moves.RazorLeaf,Moves.SecretPower,Moves.Synthesis,Moves.TeeterDance,Moves.Tickle,]), // Pkmn #044
    new Pokemon(45, "Vileplume", [Types.Grass,Types.Poison,], Rarity.Rare, 1, 3, 0, "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.", false, false, 80, 85, 75, [Moves.MegaDrain,Moves.Aromatherapy,Moves.StunSpore,Moves.PoisonPowder,Moves.PetalBlizzard,Moves.PetalDance,Moves.SolarBeam,Moves.AfterYou,Moves.Charm,Moves.Flail,Moves.Ingrain,Moves.NaturePower,Moves.RazorLeaf,Moves.SecretPower,Moves.Synthesis,Moves.TeeterDance,Moves.Tickle,]), // Pkmn #045
    new Pokemon(46, "Paras", [Types.Bug,Types.Grass,], Rarity.Common, 1, 1, 24, "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.", false, false, 70, 55, 35, [Moves.Scratch,Moves.StunSpore,Moves.PoisonPowder,Moves.LeechLife,Moves.FuryCutter,Moves.Spore,Moves.Slash,Moves.Growth,Moves.GigaDrain,Moves.Aromatherapy,Moves.RagePowder,Moves.XScissor,Moves.Agility,Moves.BugBite,Moves.Counter,Moves.CrossPoison,Moves.Endure,Moves.FellStinger,Moves.Flail,Moves.LeechSeed,Moves.MetalClaw,Moves.NaturalGift,Moves.Psybeam,Moves.Pursuit,Moves.Screech,Moves.SweetScent,]), // Pkmn #046
    new Pokemon(47, "Parasect", [Types.Bug,Types.Grass,], Rarity.Uncommon, 1, 2, 0, "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.", false, false, 95, 80, 60, [Moves.CrossPoison,Moves.Scratch,Moves.StunSpore,Moves.PoisonPowder,Moves.LeechLife,Moves.StunSpore,Moves.PoisonPowder,Moves.LeechLife,Moves.FuryCutter,Moves.Spore,Moves.Slash,Moves.Growth,Moves.GigaDrain,Moves.Aromatherapy,Moves.RagePowder,Moves.XScissor,Moves.Agility,Moves.BugBite,Moves.Counter,Moves.CrossPoison,Moves.Endure,Moves.FellStinger,Moves.Flail,Moves.LeechSeed,Moves.MetalClaw,Moves.NaturalGift,Moves.Psybeam,Moves.Pursuit,Moves.Screech,Moves.SweetScent,]), // Pkmn #047
    new Pokemon(48, "Venonat", [Types.Bug,Types.Poison,], Rarity.Common, 1, 1, 31, "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.", false, false, 55, 50, 60, [Moves.Tackle,Moves.Disable,Moves.Foresight,Moves.Supersonic,Moves.Confusion,Moves.PoisonPowder,Moves.LeechLife,Moves.StunSpore,Moves.Psybeam,Moves.SleepPowder,Moves.SignalBeam,Moves.ZenHeadbutt,Moves.PoisonFang,Moves.Psychic,Moves.Agility,Moves.BatonPass,Moves.BugBite,Moves.GigaDrain,Moves.MorningSun,Moves.RagePowder,Moves.Screech,Moves.SignalBeam,Moves.ToxicSpikes,]), // Pkmn #048
    new Pokemon(49, "Venomoth", [Types.Bug,Types.Poison,], Rarity.Uncommon, 1, 2, 0, "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.", false, false, 65, 60, 70, [Moves.QuiverDance,Moves.BugBuzz,Moves.SilverWind,Moves.Tackle,Moves.Disable,Moves.Foresight,Moves.Supersonic,Moves.Supersonic,Moves.Confusion,Moves.PoisonPowder,Moves.LeechLife,Moves.StunSpore,Moves.Psybeam,Moves.SleepPowder,Moves.Gust,Moves.SignalBeam,Moves.ZenHeadbutt,Moves.PoisonFang,Moves.Psychic,Moves.BugBuzz,Moves.QuiverDance,Moves.Agility,Moves.BatonPass,Moves.BugBite,Moves.GigaDrain,Moves.MorningSun,Moves.RagePowder,Moves.Screech,Moves.SignalBeam,Moves.ToxicSpikes,]), // Pkmn #049
    new Pokemon(50, "Digglet", [Types.Ground,], Rarity.Common, 1, 1, 26, "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.", false, false, 55, 25, 10, [Moves.Scratch,Moves.SandAttack,Moves.Growl,Moves.Astonish,Moves.MudSlap,Moves.Magnitude,Moves.Bulldoze,Moves.SuckerPunch,Moves.MudBomb,Moves.EarthPower,Moves.Dig,Moves.Slash,Moves.Earthquake,Moves.Fissure,Moves.AncientPower,Moves.Astonish,Moves.BeatUp,Moves.Endure,Moves.FeintAttack,Moves.FinalGambit,Moves.Headbutt,Moves.Memento,Moves.MudBomb,Moves.Pursuit,Moves.Reversal,Moves.Screech,Moves.Uproar,]), // Pkmn #050
    new Pokemon(51, "Dugtrio", [Types.Ground,], Rarity.Uncommon, 1, 2, 0, "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.", false, false, 80, 50, 35, [Moves.Rototiller,Moves.NightSlash,Moves.TriAttack,Moves.Scratch,Moves.SandAttack,Moves.Growl,Moves.Growl,Moves.Astonish,Moves.MudSlap,Moves.Magnitude,Moves.Bulldoze,Moves.SuckerPunch,Moves.SandTomb,Moves.MudBomb,Moves.EarthPower,Moves.Dig,Moves.Slash,Moves.Earthquake,Moves.Fissure,Moves.AncientPower,Moves.Astonish,Moves.BeatUp,Moves.Endure,Moves.FeintAttack,Moves.FinalGambit,Moves.Headbutt,Moves.Memento,Moves.MudBomb,Moves.Pursuit,Moves.Reversal,Moves.Screech,Moves.Uproar,]), // Pkmn #051
    new Pokemon(52, "Meowth", [Types.Normal,], Rarity.Common, 1, 1, 28, "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.", false, false, 45, 35, 40), // Pkmn #052
    new Pokemon(53, "Persian", [Types.Normal,], Rarity.Uncommon, 1, 2, 0, "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.", false, false, 70, 60, 65), // Pkmn #053
    new Pokemon(54, "Psyduck", [Types.Water,], Rarity.Common, 1, 1, 33, "While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.", false, false, 52, 48, 50, [Moves.WaterSport,Moves.Scratch,Moves.TailWhip,Moves.WaterGun,Moves.Disable,Moves.Confusion,Moves.WaterPulse,Moves.FurySwipes,Moves.Screech,Moves.ZenHeadbutt,Moves.AquaTail,Moves.Soak,Moves.PsychUp,Moves.Amnesia,Moves.HydroPump,Moves.WonderRoom,Moves.ClearSmog,Moves.ConfuseRay,Moves.CrossChop,Moves.Encore,Moves.Foresight,Moves.FutureSight,Moves.Hypnosis,Moves.MudBomb,Moves.Psybeam,Moves.Refresh,Moves.SecretPower,Moves.SimpleBeam,Moves.SleepTalk,Moves.Synchronoise,Moves.Yawn,]), // Pkmn #054
    new Pokemon(55, "Golduck", [Types.Water,], Rarity.Rare, 1, 2, 0, "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.", false, false, 82, 78, 80, [Moves.AquaJet,Moves.WaterSport,Moves.Scratch,Moves.TailWhip,Moves.WaterGun,Moves.TailWhip,Moves.WaterGun,Moves.Disable,Moves.Confusion,Moves.WaterPulse,Moves.FurySwipes,Moves.Screech,Moves.ZenHeadbutt,Moves.AquaTail,Moves.Soak,Moves.PsychUp,Moves.Amnesia,Moves.HydroPump,Moves.WonderRoom,Moves.ClearSmog,Moves.ConfuseRay,Moves.CrossChop,Moves.Encore,Moves.Foresight,Moves.FutureSight,Moves.Hypnosis,Moves.MudBomb,Moves.Psybeam,Moves.Refresh,Moves.SecretPower,Moves.SimpleBeam,Moves.SleepTalk,Moves.Synchronoise,Moves.Yawn,]), // Pkmn #055
    new Pokemon(56, "Mankey", [Types.Fighting,], Rarity.Common, 1, 1, 28, "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.", false, false, 80, 35, 40, [Moves.Covet,Moves.Scratch,Moves.LowKick,Moves.Leer,Moves.FocusEnergy,Moves.FurySwipes,Moves.KarateChop,Moves.SeismicToss,Moves.Screech,Moves.Assurance,Moves.Swagger,Moves.CrossChop,Moves.Thrash,Moves.Punishment,Moves.CloseCombat,Moves.FinalGambit,Moves.BeatUp,Moves.CloseCombat,Moves.Counter,Moves.Encore,Moves.FocusPunch,Moves.Foresight,Moves.Meditate,Moves.NightSlash,Moves.Revenge,Moves.Reversal,Moves.SleepTalk,Moves.SmellingSalts,]), // Pkmn #056
    new Pokemon(57, "Primeape", [Types.Fighting,], Rarity.Uncommon, 1, 2, 0, "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.", false, false, 105, 60, 65, [Moves.FinalGambit,Moves.Fling,Moves.Scratch,Moves.LowKick,Moves.Leer,Moves.FocusEnergy,Moves.FurySwipes,Moves.KarateChop,Moves.SeismicToss,Moves.Screech,Moves.Assurance,Moves.Rage,Moves.Swagger,Moves.CrossChop,Moves.Thrash,Moves.Punishment,Moves.CloseCombat,Moves.FinalGambit,Moves.BeatUp,Moves.CloseCombat,Moves.Counter,Moves.Encore,Moves.FocusPunch,Moves.Foresight,Moves.Meditate,Moves.NightSlash,Moves.Revenge,Moves.Reversal,Moves.SleepTalk,Moves.SmellingSalts,]), // Pkmn #057
    new Pokemon(58, "Growlithe", [Types.Fire,], Rarity.Common, 1, 1, 0, "Very protective of its territory. It will bark and bite to repel intruders from its space.", false, true, 70, 45, 55, [Moves.Bite,Moves.Roar,Moves.Ember,Moves.Leer,Moves.OdorSleuth,Moves.HelpingHand,Moves.FlameWheel,Moves.Reversal,Moves.FireFang,Moves.TakeDown,Moves.FlameBurst,Moves.Agility,Moves.Retaliate,Moves.Flamethrower,Moves.Crunch,Moves.HeatWave,Moves.Outrage,Moves.FlareBlitz,Moves.BodySlam,Moves.CloseCombat,Moves.Covet,Moves.Crunch,Moves.DoubleKick,Moves.DoubleEdge,Moves.FireSpin,Moves.FlareBlitz,Moves.HeatWave,Moves.Howl,Moves.IronTail,Moves.MorningSun,Moves.Thrash,]), // Pkmn #058
    new Pokemon(59, "Arcanine", [Types.Fire,], Rarity.Uncommon, 1, 2, 0, "A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.", false, false, 110, 80, 90, [Moves.ThunderFang,Moves.Bite,Moves.Roar,Moves.OdorSleuth,Moves.FireFang,Moves.ExtremeSpeed,Moves.BodySlam,Moves.CloseCombat,Moves.Covet,Moves.Crunch,Moves.DoubleKick,Moves.DoubleEdge,Moves.FireSpin,Moves.FlareBlitz,Moves.HeatWave,Moves.Howl,Moves.IronTail,Moves.MorningSun,Moves.Thrash,]), // Pkmn #059
    new Pokemon(60, "Poliwag", [Types.Water,], Rarity.Common, 1, 1, 25, "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.", false, false, 50, 40, 40, [Moves.WaterSport,Moves.Bubble,Moves.Hypnosis,Moves.WaterGun,Moves.DoubleSlap,Moves.RainDance,Moves.BodySlam,Moves.BubbleBeam,Moves.MudShot,Moves.BellyDrum,Moves.WakeUpSlap,Moves.HydroPump,Moves.MudBomb,Moves.BubbleBeam,Moves.Encore,Moves.Endeavor,Moves.Endure,Moves.Haze,Moves.IceBall,Moves.MindReader,Moves.Mist,Moves.MudShot,Moves.Refresh,Moves.Splash,Moves.WaterPulse,Moves.WaterSport,]), // Pkmn #060
    new Pokemon(61, "Poliwhirl", [Types.Water,], Rarity.Uncommon, 1, 2, 0, "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.", false, true, 65, 65, 65, [Moves.WaterSport,Moves.Bubble,Moves.Hypnosis,Moves.Bubble,Moves.Hypnosis,Moves.WaterGun,Moves.DoubleSlap,Moves.RainDance,Moves.BodySlam,Moves.BubbleBeam,Moves.MudShot,Moves.BellyDrum,Moves.WakeUpSlap,Moves.HydroPump,Moves.MudBomb,Moves.BubbleBeam,Moves.Encore,Moves.Endeavor,Moves.Endure,Moves.Haze,Moves.IceBall,Moves.MindReader,Moves.Mist,Moves.MudShot,Moves.Refresh,Moves.Splash,Moves.WaterPulse,Moves.WaterSport,]), // Pkmn #061
    new Pokemon(62, "Poliwrath", [Types.Water,Types.Fighting,], Rarity.Rare, 1, 3, 0, "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.", false, false, 95, 95, 90, [Moves.CircleThrow,Moves.BubbleBeam,Moves.Hypnosis,Moves.DoubleSlap,Moves.Submission,Moves.DynamicPunch,Moves.MindReader,Moves.CircleThrow,Moves.BubbleBeam,Moves.Encore,Moves.Endeavor,Moves.Endure,Moves.Haze,Moves.IceBall,Moves.MindReader,Moves.Mist,Moves.MudShot,Moves.Refresh,Moves.Splash,Moves.WaterPulse,Moves.WaterSport,]), // Pkmn #062
    new Pokemon(63, "Abra", [Types.Psychic,], Rarity.Common, 1, 1, 16, "Using its ability to read minds, it will identify impending danger and TELEPORT to safety.", false, false, 20, 15, 25, [Moves.Teleport,Moves.AllySwitch,Moves.Barrier,Moves.Encore,Moves.FirePunch,Moves.GuardSplit,Moves.GuardSwap,Moves.IcePunch,Moves.KnockOff,Moves.PowerTrick,Moves.PsychoShift,Moves.SkillSwap,Moves.ThunderPunch,]), // Pkmn #063
    new Pokemon(64, "Kadabra", [Types.Psychic,], Rarity.Uncommon, 1, 2, 0, "It emits special alpha waves from its body that induce headaches just by being close by.", true, false, 35, 30, 40, [Moves.Teleport,Moves.Kinesis,Moves.Confusion,Moves.Confusion,Moves.Disable,Moves.MiracleEye,Moves.AllySwitch,Moves.Psybeam,Moves.Reflect,Moves.Telekinesis,Moves.Recover,Moves.PsychoCut,Moves.RolePlay,Moves.Psychic,Moves.FutureSight,Moves.Trick,Moves.AllySwitch,Moves.Barrier,Moves.Encore,Moves.FirePunch,Moves.GuardSplit,Moves.GuardSwap,Moves.IcePunch,Moves.KnockOff,Moves.PowerTrick,Moves.PsychoShift,Moves.SkillSwap,Moves.ThunderPunch,]), // Pkmn #064
    new Pokemon(65, "Alakazam", [Types.Psychic,], Rarity.Rare, 1, 3, 0, "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.", false, false, 50, 45, 55, [Moves.Teleport,Moves.Kinesis,Moves.Confusion,Moves.Confusion,Moves.Disable,Moves.MiracleEye,Moves.AllySwitch,Moves.Psybeam,Moves.Reflect,Moves.Telekinesis,Moves.Recover,Moves.PsychoCut,Moves.CalmMind,Moves.Psychic,Moves.FutureSight,Moves.Trick,Moves.AllySwitch,Moves.Barrier,Moves.Encore,Moves.FirePunch,Moves.GuardSplit,Moves.GuardSwap,Moves.IcePunch,Moves.KnockOff,Moves.PowerTrick,Moves.PsychoShift,Moves.SkillSwap,Moves.ThunderPunch,]), // Pkmn #065
    new Pokemon(66, "Machop", [Types.Fighting,], Rarity.Common, 1, 1, 28, "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.", false, false, 80, 50, 70, [Moves.LowKick,Moves.Leer,Moves.FocusEnergy,Moves.KarateChop,Moves.LowSweep,Moves.Foresight,Moves.SeismicToss,Moves.Revenge,Moves.VitalThrow,Moves.Submission,Moves.WakeUpSlap,Moves.CrossChop,Moves.ScaryFace,Moves.DynamicPunch,Moves.BulletPunch,Moves.CloseCombat,Moves.Counter,Moves.Encore,Moves.FirePunch,Moves.HeavySlam,Moves.IcePunch,Moves.KnockOff,Moves.Meditate,Moves.PowerTrick,Moves.QuickGuard,Moves.RollingKick,Moves.SmellingSalts,Moves.ThunderPunch,Moves.Tickle,]), // Pkmn #066
    new Pokemon(67, "Machoke", [Types.Fighting,], Rarity.Uncommon, 1, 2, 0, "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.", true, false, 100, 70, 80, [Moves.LowKick,Moves.Leer,Moves.FocusEnergy,Moves.KarateChop,Moves.FocusEnergy,Moves.KarateChop,Moves.LowSweep,Moves.Foresight,Moves.SeismicToss,Moves.Revenge,Moves.VitalThrow,Moves.Submission,Moves.WakeUpSlap,Moves.CrossChop,Moves.ScaryFace,Moves.DynamicPunch,Moves.BulletPunch,Moves.CloseCombat,Moves.Counter,Moves.Encore,Moves.FirePunch,Moves.HeavySlam,Moves.IcePunch,Moves.KnockOff,Moves.Meditate,Moves.PowerTrick,Moves.QuickGuard,Moves.RollingKick,Moves.SmellingSalts,Moves.ThunderPunch,Moves.Tickle,]), // Pkmn #067
    new Pokemon(68, "Machamp", [Types.Fighting,], Rarity.Rare, 1, 3, 0, "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.", false, false, 130, 80, 90, [Moves.WideGuard,Moves.LowKick,Moves.Leer,Moves.FocusEnergy,Moves.KarateChop,Moves.FocusEnergy,Moves.KarateChop,Moves.LowSweep,Moves.Foresight,Moves.SeismicToss,Moves.Revenge,Moves.VitalThrow,Moves.Submission,Moves.WakeUpSlap,Moves.CrossChop,Moves.ScaryFace,Moves.DynamicPunch,Moves.BulletPunch,Moves.CloseCombat,Moves.Counter,Moves.Encore,Moves.FirePunch,Moves.HeavySlam,Moves.IcePunch,Moves.KnockOff,Moves.Meditate,Moves.PowerTrick,Moves.QuickGuard,Moves.RollingKick,Moves.SmellingSalts,Moves.ThunderPunch,Moves.Tickle,]), // Pkmn #068
    new Pokemon(69, "Bellsprout", [Types.Grass,Types.Poison,], Rarity.Common, 1, 1, 21, "A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.", false, false, 75, 35, 50, [Moves.VineWhip,Moves.Growth,Moves.Wrap,Moves.SleepPowder,Moves.PoisonPowder,Moves.StunSpore,Moves.Acid,Moves.KnockOff,Moves.SweetScent,Moves.GastroAcid,Moves.RazorLeaf,Moves.Slam,Moves.WringOut,Moves.AcidSpray,Moves.Belch,Moves.BulletSeed,Moves.ClearSmog,Moves.Encore,Moves.GigaDrain,Moves.Ingrain,Moves.LeechLife,Moves.MagicalLeaf,Moves.NaturalGift,Moves.PowerWhip,Moves.Synthesis,Moves.Tickle,Moves.WeatherBall,Moves.WorrySeed,]), // Pkmn #069
    new Pokemon(70, "Weepinbell", [Types.Grass,Types.Poison,], Rarity.Uncommon, 1, 2, 0, "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.", false, true, 90, 50, 65, [Moves.VineWhip,Moves.Growth,Moves.Wrap,Moves.Growth,Moves.Wrap,Moves.SleepPowder,Moves.PoisonPowder,Moves.StunSpore,Moves.Acid,Moves.KnockOff,Moves.SweetScent,Moves.GastroAcid,Moves.RazorLeaf,Moves.Slam,Moves.WringOut,Moves.AcidSpray,Moves.Belch,Moves.BulletSeed,Moves.ClearSmog,Moves.Encore,Moves.GigaDrain,Moves.Ingrain,Moves.LeechLife,Moves.MagicalLeaf,Moves.NaturalGift,Moves.PowerWhip,Moves.Synthesis,Moves.Tickle,Moves.WeatherBall,Moves.WorrySeed,]), // Pkmn #070
    new Pokemon(71, "Victreebel", [Types.Grass,Types.Poison,], Rarity.Rare, 1, 3, 0, "Said to live in huge colonies deep in jungles, although no one has ever returned from there.", false, false, 105, 65, 80, [Moves.Stockpile,Moves.Swallow,Moves.SpitUp,Moves.VineWhip,Moves.SleepPowder,Moves.SweetScent,Moves.RazorLeaf,Moves.LeafTornado,Moves.LeafStorm,Moves.LeafBlade,Moves.AcidSpray,Moves.Belch,Moves.BulletSeed,Moves.ClearSmog,Moves.Encore,Moves.GigaDrain,Moves.Ingrain,Moves.LeechLife,Moves.MagicalLeaf,Moves.NaturalGift,Moves.PowerWhip,Moves.Synthesis,Moves.Tickle,Moves.WeatherBall,Moves.WorrySeed,]), // Pkmn #071
    new Pokemon(72, "Tentacool", [Types.Water,Types.Poison,], Rarity.Common, 1, 1, 30, "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.", false, false, 40, 35, 40, [Moves.PoisonSting,Moves.Supersonic,Moves.Constrict,Moves.Acid,Moves.ToxicSpikes,Moves.BubbleBeam,Moves.Wrap,Moves.AcidSpray,Moves.Barrier,Moves.WaterPulse,Moves.PoisonJab,Moves.Screech,Moves.Hex,Moves.HydroPump,Moves.SludgeWave,Moves.WringOut,Moves.Acupressure,Moves.AquaRing,Moves.AuroraBeam,Moves.Bubble,Moves.ConfuseRay,Moves.Haze,Moves.KnockOff,Moves.MirrorCoat,Moves.MuddyWater,Moves.RapidSpin,Moves.Tickle,]), // Pkmn #072
    new Pokemon(73, "Tentacruel", [Types.Water,Types.Poison,], Rarity.Uncommon, 1, 2, 0, "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.", false, false, 70, 65, 80, [Moves.ReflectType,Moves.WringOut,Moves.PoisonSting,Moves.Supersonic,Moves.Constrict,Moves.Supersonic,Moves.Constrict,Moves.Acid,Moves.ToxicSpikes,Moves.BubbleBeam,Moves.Wrap,Moves.AcidSpray,Moves.Barrier,Moves.WaterPulse,Moves.PoisonJab,Moves.Screech,Moves.Hex,Moves.HydroPump,Moves.SludgeWave,Moves.WringOut,Moves.Acupressure,Moves.AquaRing,Moves.AuroraBeam,Moves.Bubble,Moves.ConfuseRay,Moves.Haze,Moves.KnockOff,Moves.MirrorCoat,Moves.MuddyWater,Moves.RapidSpin,Moves.Tickle,]), // Pkmn #073
    new Pokemon(74, "Geodude", [Types.Rock,Types.Ground,], Rarity.Common, 1, 1, 25, "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.", false, false, 80, 100, 40, [Moves.Tackle,Moves.DefenseCurl,Moves.MudSport,Moves.RockPolish,Moves.Rollout,Moves.Magnitude,Moves.RockThrow,Moves.RockBlast,Moves.SmackDown,Moves.SelfDestruct,Moves.Bulldoze,Moves.StealthRock,Moves.Earthquake,Moves.Explosion,Moves.DoubleEdge,Moves.StoneEdge,Moves.Autotomize,Moves.Block,Moves.Curse,Moves.Endure,Moves.Flail,Moves.FocusPunch,Moves.HammerArm,Moves.MegaPunch,Moves.RockClimb,Moves.WideGuard,]), // Pkmn #074
    new Pokemon(75, "Graveler", [Types.Rock,Types.Ground,], Rarity.Uncommon, 1, 2, 0, "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.", true, false, 95, 115, 55, [Moves.Tackle,Moves.DefenseCurl,Moves.MudSport,Moves.RockPolish,Moves.Rollout,Moves.Magnitude,Moves.RockThrow,Moves.RockBlast,Moves.SmackDown,Moves.SelfDestruct,Moves.Bulldoze,Moves.StealthRock,Moves.Earthquake,Moves.Explosion,Moves.DoubleEdge,Moves.StoneEdge,Moves.Autotomize,Moves.Block,Moves.Curse,Moves.Endure,Moves.Flail,Moves.FocusPunch,Moves.HammerArm,Moves.MegaPunch,Moves.RockClimb,Moves.WideGuard,]), // Pkmn #075
    new Pokemon(76, "Golem", [Types.Rock,Types.Ground,], Rarity.Rare, 1, 3, 0, "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.", false, false, 120, 130, 80, [Moves.HeavySlam,Moves.Tackle,Moves.DefenseCurl,Moves.MudSport,Moves.RockPolish,Moves.Steamroller,Moves.Magnitude,Moves.RockThrow,Moves.RockBlast,Moves.SmackDown,Moves.SelfDestruct,Moves.Bulldoze,Moves.StealthRock,Moves.Earthquake,Moves.Explosion,Moves.DoubleEdge,Moves.StoneEdge,Moves.HeavySlam,Moves.Autotomize,Moves.Block,Moves.Curse,Moves.Endure,Moves.Flail,Moves.FocusPunch,Moves.HammerArm,Moves.MegaPunch,Moves.RockClimb,Moves.WideGuard,]), // Pkmn #076
    new Pokemon(77, "Ponyta", [Types.Fire,], Rarity.Common, 1, 1, 40, "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.", false, false, 85, 55, 50, [Moves.Growl,Moves.Tackle,Moves.TailWhip,Moves.Ember,Moves.FlameWheel,Moves.Stomp,Moves.FlameCharge,Moves.FireSpin,Moves.TakeDown,Moves.Inferno,Moves.Agility,Moves.FireBlast,Moves.Bounce,Moves.FlareBlitz,Moves.AllySwitch,Moves.Captivate,Moves.Charm,Moves.DoubleKick,Moves.DoubleEdge,Moves.FlameWheel,Moves.HornDrill,Moves.Hypnosis,Moves.LowKick,Moves.MorningSun,Moves.Thrash,]), // Pkmn #077
    new Pokemon(78, "Rapidash", [Types.Fire,], Rarity.Uncommon, 1, 2, 0, "Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it.", false, false, 100, 70, 65, [Moves.PoisonJab,Moves.Megahorn,Moves.Growl,Moves.QuickAttack,Moves.TailWhip,Moves.Ember,Moves.TailWhip,Moves.Ember,Moves.FlameWheel,Moves.Stomp,Moves.FlameCharge,Moves.FireSpin,Moves.TakeDown,Moves.Inferno,Moves.Agility,Moves.FuryAttack,Moves.FireBlast,Moves.Bounce,Moves.FlareBlitz,Moves.AllySwitch,Moves.Captivate,Moves.Charm,Moves.DoubleKick,Moves.DoubleEdge,Moves.FlameWheel,Moves.HornDrill,Moves.Hypnosis,Moves.LowKick,Moves.MorningSun,Moves.Thrash,]), // Pkmn #078
    new Pokemon(79, "Slowpoke", [Types.Water,Types.Psychic,], Rarity.Common, 1, 1, 37, "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.", false, false, 65, 65, 90, [Moves.Curse,Moves.Yawn,Moves.Tackle,Moves.Growl,Moves.WaterGun,Moves.Confusion,Moves.Disable,Moves.Headbutt,Moves.WaterPulse,Moves.ZenHeadbutt,Moves.SlackOff,Moves.Amnesia,Moves.Psychic,Moves.RainDance,Moves.PsychUp,Moves.HealPulse,Moves.Belch,Moves.BellyDrum,Moves.Block,Moves.FutureSight,Moves.MeFirst,Moves.MudSport,Moves.SleepTalk,Moves.Snore,Moves.Stomp,Moves.WonderRoom,Moves.ZenHeadbutt,]), // Pkmn #079
    new Pokemon(80, "Slowbro", [Types.Water,Types.Psychic,], Rarity.Uncommon, 1, 2, 0, "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps.", false, false, 75, 110, 95, [Moves.HealPulse,Moves.Curse,Moves.Yawn,Moves.Tackle,Moves.Growl,Moves.Growl,Moves.WaterGun,Moves.Confusion,Moves.Disable,Moves.Headbutt,Moves.WaterPulse,Moves.ZenHeadbutt,Moves.SlackOff,Moves.Withdraw,Moves.Amnesia,Moves.Psychic,Moves.RainDance,Moves.PsychUp,Moves.HealPulse,Moves.Belch,Moves.BellyDrum,Moves.Block,Moves.FutureSight,Moves.MeFirst,Moves.MudSport,Moves.SleepTalk,Moves.Snore,Moves.Stomp,Moves.WonderRoom,Moves.ZenHeadbutt,]), // Pkmn #080
    new Pokemon(81, "Magnemite", [Types.Electric,Types.Steel,], Rarity.Common, 1, 1, 30, "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.", false, false, 35, 70, 25, [Moves.Tackle,Moves.Supersonic,Moves.ThunderShock,Moves.SonicBoom,Moves.ThunderWave,Moves.MagnetBomb,Moves.Spark,Moves.MirrorShot,Moves.MetalSound,Moves.ElectroBall,Moves.FlashCannon,Moves.Screech,Moves.Discharge,Moves.LockOn,Moves.MagnetRise,Moves.GyroBall,Moves.ZapCannon,]), // Pkmn #081
    new Pokemon(82, "Magneton", [Types.Electric,Types.Steel,], Rarity.Uncommon, 1, 2, 0, "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.", false, false, 60, 95, 50, [Moves.ZapCannon,Moves.TriAttack,Moves.Tackle,Moves.Supersonic,Moves.ThunderShock,Moves.SonicBoom,Moves.Supersonic,Moves.ThunderShock,Moves.ElectricTerrain,Moves.ThunderWave,Moves.MagnetBomb,Moves.Spark,Moves.MirrorShot,Moves.MetalSound,Moves.ElectroBall,Moves.FlashCannon,Moves.Screech,Moves.Discharge,Moves.LockOn,Moves.MagnetRise,Moves.GyroBall,Moves.ZapCannon,]), // Pkmn #082
    new Pokemon(83, "Farfetch'd", [Types.Normal,Types.Flying,], Rarity.Uncommon, 1, 1, 0, "The sprig of green onions it holds is its weapon. It is used much like a metal sword.", false, false, 65, 55, 52, [Moves.BraveBird,Moves.PoisonJab,Moves.Peck,Moves.SandAttack,Moves.Leer,Moves.FuryCutter,Moves.FuryAttack,Moves.AerialAce,Moves.KnockOff,Moves.Slash,Moves.AirCutter,Moves.SwordsDance,Moves.Agility,Moves.NightSlash,Moves.Acrobatics,Moves.Feint,Moves.FalseSwipe,Moves.AirSlash,Moves.BraveBird,Moves.Covet,Moves.Curse,Moves.FeatherDance,Moves.Flail,Moves.Foresight,Moves.Gust,Moves.LeafBlade,Moves.MirrorMove,Moves.MudSlap,Moves.NightSlash,Moves.QuickAttack,Moves.Revenge,Moves.Roost,Moves.SimpleBeam,Moves.SteelWing,Moves.TrumpCard,]), // Pkmn #083
    new Pokemon(84, "Doduo", [Types.Normal,Types.Flying,], Rarity.Common, 1, 1, 31, "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.", false, false, 85, 45, 35, [Moves.Peck,Moves.Growl,Moves.QuickAttack,Moves.Rage,Moves.FuryAttack,Moves.Pursuit,Moves.Uproar,Moves.Acupressure,Moves.DoubleHit,Moves.Agility,Moves.DrillPeck,Moves.Endeavor,Moves.Thrash,Moves.Assurance,Moves.BraveBird,Moves.Endeavor,Moves.FeintAttack,Moves.Flail,Moves.Haze,Moves.MirrorMove,Moves.NaturalGift,Moves.QuickAttack,Moves.Supersonic,]), // Pkmn #084
    new Pokemon(85, "Dodrio", [Types.Normal,Types.Flying,], Rarity.Uncommon, 1, 2, 0, "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.", false, false, 110, 70, 60, [Moves.Pluck,Moves.Peck,Moves.Growl,Moves.QuickAttack,Moves.Rage,Moves.QuickAttack,Moves.Rage,Moves.FuryAttack,Moves.Pursuit,Moves.Uproar,Moves.Acupressure,Moves.TriAttack,Moves.Agility,Moves.DrillPeck,Moves.Endeavor,Moves.Thrash,Moves.Assurance,Moves.BraveBird,Moves.Endeavor,Moves.FeintAttack,Moves.Flail,Moves.Haze,Moves.MirrorMove,Moves.NaturalGift,Moves.QuickAttack,Moves.Supersonic,]), // Pkmn #085
    new Pokemon(86, "Seel", [Types.Water,], Rarity.Common, 1, 1, 34, "The protruding horn on its head is very hard. It is used for bashing through thick ice.", false, false, 45, 55, 65, [Moves.Headbutt,Moves.Growl,Moves.WaterSport,Moves.IcyWind,Moves.Encore,Moves.IceShard,Moves.Rest,Moves.AquaRing,Moves.AuroraBeam,Moves.AquaJet,Moves.Brine,Moves.TakeDown,Moves.Dive,Moves.AquaTail,Moves.IceBeam,Moves.Safeguard,Moves.Hail,Moves.Belch,Moves.Disable,Moves.Encore,Moves.Entrainment,Moves.FakeOut,Moves.HornDrill,Moves.IcicleSpear,Moves.IronTail,Moves.Lick,Moves.PerishSong,Moves.SignalBeam,Moves.Slam,Moves.SleepTalk,Moves.SpitUp,Moves.Stockpile,Moves.Swallow,Moves.WaterPulse,]), // Pkmn #086
    new Pokemon(87, "Dewgong", [Types.Water,Types.Ice,], Rarity.Uncommon, 1, 2, 0, "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.", false, false, 70, 80, 90, [Moves.Headbutt,Moves.Growl,Moves.SignalBeam,Moves.IcyWind,Moves.Growl,Moves.SignalBeam,Moves.IcyWind,Moves.Encore,Moves.IceShard,Moves.Rest,Moves.AquaRing,Moves.AuroraBeam,Moves.AquaJet,Moves.Brine,Moves.SheerCold,Moves.TakeDown,Moves.Dive,Moves.AquaTail,Moves.IceBeam,Moves.Safeguard,Moves.Hail,Moves.Belch,Moves.Disable,Moves.Encore,Moves.Entrainment,Moves.FakeOut,Moves.HornDrill,Moves.IcicleSpear,Moves.IronTail,Moves.Lick,Moves.PerishSong,Moves.SignalBeam,Moves.Slam,Moves.SleepTalk,Moves.SpitUp,Moves.Stockpile,Moves.Swallow,Moves.WaterPulse,]), // Pkmn #087
    new Pokemon(88, "Grimer", [Types.Poison,], Rarity.Common, 1, 1, 38, "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.", false, false, 80, 50, 80, [Moves.Pound,Moves.PoisonGas,Moves.Harden,Moves.MudSlap,Moves.Disable,Moves.Sludge,Moves.Minimize,Moves.MudBomb,Moves.SludgeBomb,Moves.Fling,Moves.Screech,Moves.SludgeWave,Moves.AcidArmor,Moves.GunkShot,Moves.Belch,Moves.Memento,Moves.AcidSpray,Moves.Curse,Moves.Imprison,Moves.Lick,Moves.MeanLook,Moves.ScaryFace,Moves.ShadowPunch,Moves.ShadowSneak,Moves.SpitUp,Moves.Stockpile,Moves.Swallow,]), // Pkmn #088
    new Pokemon(89, "Muk", [Types.Poison,], Rarity.Uncommon, 1, 2, 0, "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.", false, false, 105, 75, 105, [Moves.Pound,Moves.PoisonGas,Moves.Harden,Moves.MudSlap,Moves.Harden,Moves.MudSlap,Moves.Disable,Moves.Sludge,Moves.Minimize,Moves.MudBomb,Moves.SludgeBomb,Moves.Fling,Moves.Screech,Moves.SludgeWave,Moves.AcidArmor,Moves.GunkShot,Moves.Belch,Moves.Memento,Moves.AcidSpray,Moves.Curse,Moves.Imprison,Moves.Lick,Moves.MeanLook,Moves.ScaryFace,Moves.ShadowPunch,Moves.ShadowSneak,Moves.SpitUp,Moves.Stockpile,Moves.Swallow,]), // Pkmn #089
    new Pokemon(90, "Shellder", [Types.Water,], Rarity.Common, 1, 1, 0, "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.", false, true, 65, 100, 30, [Moves.Tackle,Moves.Withdraw,Moves.Supersonic,Moves.IcicleSpear,Moves.Protect,Moves.Leer,Moves.Clamp,Moves.IceShard,Moves.RazorShell,Moves.AuroraBeam,Moves.Whirlpool,Moves.Brine,Moves.IronDefense,Moves.IceBeam,Moves.ShellSmash,Moves.HydroPump,Moves.AquaRing,Moves.Avalanche,Moves.Barrier,Moves.BubbleBeam,Moves.IcicleSpear,Moves.MudShot,Moves.RapidSpin,Moves.RockBlast,Moves.Screech,Moves.TakeDown,Moves.Twineedle,Moves.WaterPulse,]), // Pkmn #090
    new Pokemon(91, "Cloyster", [Types.Water,Types.Ice,], Rarity.Uncommon, 1, 2, 0, "When attacked, it launches its horns in quick volleys. Its innards have never been seen.", false, false, 95, 180, 50, [Moves.HydroPump,Moves.ShellSmash,Moves.ToxicSpikes,Moves.Withdraw,Moves.Supersonic,Moves.Protect,Moves.AuroraBeam,Moves.SpikeCannon,Moves.Spikes,Moves.IcicleCrash,Moves.AquaRing,Moves.Avalanche,Moves.Barrier,Moves.BubbleBeam,Moves.IcicleSpear,Moves.MudShot,Moves.RapidSpin,Moves.RockBlast,Moves.Screech,Moves.TakeDown,Moves.Twineedle,Moves.WaterPulse,]), // Pkmn #091
    new Pokemon(92, "Gastly", [Types.Ghost,Types.Poison,], Rarity.Common, 1, 1, 25, "Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.", false, false, 35, 30, 30, [Moves.Hypnosis,Moves.Lick,Moves.Spite,Moves.MeanLook,Moves.Curse,Moves.NightShade,Moves.ConfuseRay,Moves.SuckerPunch,Moves.Payback,Moves.ShadowBall,Moves.DreamEater,Moves.DarkPulse,Moves.DestinyBond,Moves.Hex,Moves.Nightmare,Moves.Astonish,Moves.ClearSmog,Moves.Disable,Moves.FirePunch,Moves.Grudge,Moves.Haze,Moves.IcePunch,Moves.PerishSong,Moves.Psywave,Moves.ReflectType,Moves.ScaryFace,Moves.Smog,Moves.ThunderPunch,]), // Pkmn #092
    new Pokemon(93, "Haunter", [Types.Ghost,Types.Poison,], Rarity.Uncommon, 1, 2, 0, "Because of its ability to slip through block walls, it is said to be from another dimension.", true, false, 50, 45, 45, [Moves.Hypnosis,Moves.Lick,Moves.Spite,Moves.Spite,Moves.MeanLook,Moves.Curse,Moves.NightShade,Moves.ConfuseRay,Moves.SuckerPunch,Moves.ShadowPunch,Moves.Payback,Moves.ShadowBall,Moves.DreamEater,Moves.DarkPulse,Moves.DestinyBond,Moves.Hex,Moves.Nightmare,Moves.Astonish,Moves.ClearSmog,Moves.Disable,Moves.FirePunch,Moves.Grudge,Moves.Haze,Moves.IcePunch,Moves.PerishSong,Moves.Psywave,Moves.ReflectType,Moves.ScaryFace,Moves.Smog,Moves.ThunderPunch,]), // Pkmn #093
    new Pokemon(94, "Gengar", [Types.Ghost,Types.Poison,], Rarity.Rare, 1, 3, 0, "Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.", false, false, 65, 60, 60, [Moves.Hypnosis,Moves.Lick,Moves.Spite,Moves.Spite,Moves.MeanLook,Moves.Curse,Moves.NightShade,Moves.ConfuseRay,Moves.SuckerPunch,Moves.ShadowPunch,Moves.Payback,Moves.ShadowBall,Moves.DreamEater,Moves.DarkPulse,Moves.DestinyBond,Moves.Hex,Moves.Nightmare,Moves.Astonish,Moves.ClearSmog,Moves.Disable,Moves.FirePunch,Moves.Grudge,Moves.Haze,Moves.IcePunch,Moves.PerishSong,Moves.Psywave,Moves.ReflectType,Moves.ScaryFace,Moves.Smog,Moves.ThunderPunch,]), // Pkmn #094
    new Pokemon(95, "Onix", [Types.Rock,Types.Ground,], Rarity.Common, 1, 1, 0, "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.", false, false, 45, 160, 35, [Moves.MudSport,Moves.Tackle,Moves.Harden,Moves.Bind,Moves.Curse,Moves.RockThrow,Moves.RockTomb,Moves.Rage,Moves.StealthRock,Moves.RockPolish,Moves.SmackDown,Moves.DragonBreath,Moves.Slam,Moves.Screech,Moves.RockSlide,Moves.SandTomb,Moves.IronTail,Moves.Dig,Moves.StoneEdge,Moves.DoubleEdge,Moves.Sandstorm,Moves.Block,Moves.DefenseCurl,Moves.Flail,Moves.HeavySlam,Moves.RockBlast,Moves.RockClimb,Moves.Rollout,Moves.Rototiller,Moves.StealthRock,]), // Pkmn #095
    new Pokemon(96, "Drowzee", [Types.Psychic,], Rarity.Common, 1, 1, 26, "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.", false, false, 48, 45, 60, [Moves.Pound,Moves.Hypnosis,Moves.Disable,Moves.Confusion,Moves.Headbutt,Moves.PoisonGas,Moves.Meditate,Moves.Psybeam,Moves.Headbutt,Moves.PsychUp,Moves.Synchronoise,Moves.ZenHeadbutt,Moves.Swagger,Moves.Psychic,Moves.NastyPlot,Moves.Psyshock,Moves.FutureSight,Moves.Assist,Moves.Barrier,Moves.FirePunch,Moves.Flatter,Moves.GuardSwap,Moves.IcePunch,Moves.NastyPlot,Moves.PsychoCut,Moves.RolePlay,Moves.ThunderPunch,]), // Pkmn #096
    new Pokemon(97, "Hypno", [Types.Psychic,], Rarity.Uncommon, 1, 2, 0, "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.", false, false, 73, 70, 85, [Moves.FutureSight,Moves.NastyPlot,Moves.Nightmare,Moves.Switcheroo,Moves.Pound,Moves.Hypnosis,Moves.Disable,Moves.Confusion,Moves.Disable,Moves.Confusion,Moves.Headbutt,Moves.PoisonGas,Moves.Meditate,Moves.Psybeam,Moves.Headbutt,Moves.PsychUp,Moves.Synchronoise,Moves.ZenHeadbutt,Moves.Swagger,Moves.Psychic,Moves.NastyPlot,Moves.Psyshock,Moves.FutureSight,Moves.Assist,Moves.Barrier,Moves.FirePunch,Moves.Flatter,Moves.GuardSwap,Moves.IcePunch,Moves.NastyPlot,Moves.PsychoCut,Moves.RolePlay,Moves.ThunderPunch,]), // Pkmn #097
    new Pokemon(98, "Krabby", [Types.Water,], Rarity.Common, 1, 1, 28, "Its pincers are not only powerful weapons, they are used for balance when walking sideways.", false, false, 105, 90, 30, [Moves.MudSport,Moves.Bubble,Moves.ViceGrip,Moves.Leer,Moves.Harden,Moves.BubbleBeam,Moves.MudShot,Moves.MetalClaw,Moves.Stomp,Moves.Protect,Moves.Guillotine,Moves.Slam,Moves.Brine,Moves.Crabhammer,Moves.Flail,Moves.Agility,Moves.Amnesia,Moves.AncientPower,Moves.Bide,Moves.Endure,Moves.Flail,Moves.Haze,Moves.KnockOff,Moves.Tickle,]), // Pkmn #098
    new Pokemon(99, "Kingler", [Types.Water,], Rarity.Uncommon, 1, 2, 0, "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.", false, false, 130, 115, 55, [Moves.WideGuard,Moves.MudSport,Moves.Bubble,Moves.ViceGrip,Moves.Leer,Moves.ViceGrip,Moves.Leer,Moves.Harden,Moves.BubbleBeam,Moves.MudShot,Moves.MetalClaw,Moves.Stomp,Moves.Protect,Moves.Guillotine,Moves.Slam,Moves.Brine,Moves.Crabhammer,Moves.Flail,Moves.Agility,Moves.Amnesia,Moves.AncientPower,Moves.Bide,Moves.Endure,Moves.Flail,Moves.Haze,Moves.KnockOff,Moves.Tickle,]), // Pkmn #099
    new Pokemon(100, "Voltorb", [Types.Electric,], Rarity.Common, 1, 1, 30, "Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people.", false, false, 30, 50, 40, [Moves.Charge,Moves.Tackle,Moves.SonicBoom,Moves.EerieImpulse,Moves.Spark,Moves.Rollout,Moves.Screech,Moves.ChargeBeam,Moves.LightScreen,Moves.ElectroBall,Moves.SelfDestruct,Moves.Swift,Moves.MagnetRise,Moves.GyroBall,Moves.Explosion,Moves.MirrorCoat,]), // Pkmn #100
    new Pokemon(101, "Electrode", [Types.Electric,], Rarity.Uncommon, 1, 2, 0, "It stores electric energy under very high pressure. It often explodes with little or no provocation.", false, false, 50, 70, 60, [Moves.MagneticFlux,Moves.Charge,Moves.Tackle,Moves.SonicBoom,Moves.Spark,Moves.Tackle,Moves.EerieImpulse,Moves.Spark,Moves.Rollout,Moves.Screech,Moves.ChargeBeam,Moves.LightScreen,Moves.ElectroBall,Moves.SelfDestruct,Moves.Swift,Moves.MagnetRise,Moves.GyroBall,Moves.Explosion,Moves.MirrorCoat,]), // Pkmn #101
    new Pokemon(102, "Exeggcute", [Types.Grass,Types.Psychic,], Rarity.Common, 1, 1, 0, "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.", false, true, 40, 80, 60, [Moves.Barrage,Moves.Uproar,Moves.Hypnosis,Moves.Reflect,Moves.LeechSeed,Moves.BulletSeed,Moves.StunSpore,Moves.PoisonPowder,Moves.SleepPowder,Moves.Confusion,Moves.WorrySeed,Moves.NaturalGift,Moves.SolarBeam,Moves.Extrasensory,Moves.Bestow,Moves.AncientPower,Moves.Block,Moves.Curse,Moves.GigaDrain,Moves.GrassyTerrain,Moves.Ingrain,Moves.LeafStorm,Moves.LuckyChant,Moves.Moonlight,Moves.NaturalGift,Moves.NaturePower,Moves.PowerSwap,Moves.SkillSwap,Moves.Synthesis,]), // Pkmn #102
    new Pokemon(103, "Exeggutor", [Types.Grass,Types.Psychic,], Rarity.Uncommon, 1, 2, 0, "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.", false, false, 95, 85, 95, [Moves.SeedBomb,Moves.Barrage,Moves.Hypnosis,Moves.Confusion,Moves.Stomp,Moves.Psyshock,Moves.EggBomb,Moves.WoodHammer,Moves.LeafStorm,Moves.AncientPower,Moves.Block,Moves.Curse,Moves.GigaDrain,Moves.GrassyTerrain,Moves.Ingrain,Moves.LeafStorm,Moves.LuckyChant,Moves.Moonlight,Moves.NaturalGift,Moves.NaturePower,Moves.PowerSwap,Moves.SkillSwap,Moves.Synthesis,]), // Pkmn #103
    new Pokemon(104, "Cubone", [Types.Ground,], Rarity.Common, 1, 1, 28, "Because it never removes its skull helmet, no one has ever seen this POKéMON's real face.", false, false, 50, 95, 50, [Moves.Growl,Moves.TailWhip,Moves.BoneClub,Moves.Headbutt,Moves.Leer,Moves.FocusEnergy,Moves.Bonemerang,Moves.Rage,Moves.FalseSwipe,Moves.Thrash,Moves.Fling,Moves.BoneRush,Moves.Endeavor,Moves.DoubleEdge,Moves.Retaliate,Moves.AncientPower,Moves.BellyDrum,Moves.ChipAway,Moves.Detect,Moves.DoubleKick,Moves.Endure,Moves.IronHead,Moves.PerishSong,Moves.Screech,Moves.SkullBash,]), // Pkmn #104
    new Pokemon(105, "Marowak", [Types.Ground,], Rarity.Uncommon, 1, 2, 0, "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.", false, false, 80, 110, 60, [Moves.Growl,Moves.TailWhip,Moves.BoneClub,Moves.Headbutt,Moves.TailWhip,Moves.BoneClub,Moves.Headbutt,Moves.Leer,Moves.FocusEnergy,Moves.Bonemerang,Moves.Rage,Moves.FalseSwipe,Moves.Thrash,Moves.Fling,Moves.BoneRush,Moves.Endeavor,Moves.DoubleEdge,Moves.Retaliate,Moves.AncientPower,Moves.BellyDrum,Moves.ChipAway,Moves.Detect,Moves.DoubleKick,Moves.Endure,Moves.IronHead,Moves.PerishSong,Moves.Screech,Moves.SkullBash,]), // Pkmn #105
    new Pokemon(106, "Hitmonlee", [Types.Fighting,], Rarity.Rare, 1, 1, 0, "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.", false, false, 120, 53, 50, [Moves.Reversal,Moves.CloseCombat,Moves.MegaKick,Moves.Revenge,Moves.DoubleKick,Moves.Meditate,Moves.RollingKick,Moves.JumpKick,Moves.BrickBreak,Moves.FocusEnergy,Moves.Feint,Moves.HighJumpKick,Moves.MindReader,Moves.Foresight,Moves.WideGuard,Moves.BlazeKick,Moves.Endure,Moves.MegaKick,Moves.CloseCombat,Moves.Reversal,Moves.BulletPunch,Moves.Counter,Moves.Endure,Moves.Feint,Moves.HighJumpKick,Moves.MachPunch,Moves.MindReader,Moves.Pursuit,Moves.RapidSpin,Moves.VacuumWave,]), // Pkmn #106
    new Pokemon(107, "Hitmonchan", [Types.Fighting,], Rarity.Rare, 1, 1, 0, "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.", false, false, 105, 79, 50, [Moves.CloseCombat,Moves.Counter,Moves.FocusPunch,Moves.Revenge,Moves.CometPunch,Moves.Agility,Moves.Pursuit,Moves.MachPunch,Moves.BulletPunch,Moves.Feint,Moves.VacuumWave,Moves.QuickGuard,Moves.ThunderPunch,Moves.IcePunch,Moves.FirePunch,Moves.SkyUppercut,Moves.MegaPunch,Moves.Detect,Moves.FocusPunch,Moves.Counter,Moves.CloseCombat,Moves.BulletPunch,Moves.Counter,Moves.Endure,Moves.Feint,Moves.HighJumpKick,Moves.MachPunch,Moves.MindReader,Moves.Pursuit,Moves.RapidSpin,Moves.VacuumWave,]), // Pkmn #107
    new Pokemon(108, "Lickitung", [Types.Normal,], Rarity.Uncommon, 1, 1, 0, "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.", false, false, 55, 75, 90, [Moves.Lick,Moves.Supersonic,Moves.DefenseCurl,Moves.KnockOff,Moves.Wrap,Moves.Stomp,Moves.Disable,Moves.Slam,Moves.Rollout,Moves.ChipAway,Moves.MeFirst,Moves.Refresh,Moves.Screech,Moves.PowerWhip,Moves.WringOut,Moves.Amnesia,Moves.Belch,Moves.BellyDrum,Moves.BodySlam,Moves.Curse,Moves.HammerArm,Moves.Magnitude,Moves.MuddyWater,Moves.SleepTalk,Moves.SmellingSalts,Moves.Snore,Moves.ZenHeadbutt,]), // Pkmn #108
    new Pokemon(109, "Koffing", [Types.Poison,], Rarity.Common, 1, 1, 35, "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.", false, false, 65, 95, 40), // Pkmn #109
    new Pokemon(110, "Weezing", [Types.Poison,], Rarity.Uncommon, 1, 2, 0, "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.", false, false, 90, 120, 65), // Pkmn #110
    new Pokemon(111, "Rhyhorn", [Types.Rock, Types.Ground, ], Rarity.Common, 1, 1, 42, `Rhyhorn’s brain is very small. It is so dense, while on a run it forgets why it started running in the first place. It apparently remembers sometimes if it demolishes something.`, false, false, 85, 95, 80, [Moves.SwordsDance, Moves.Stomp, Moves.HornAttack, Moves.FuryAttack, Moves.HornDrill, Moves.TakeDown, Moves.Thrash, Moves.TailWhip, Moves.Leer, Moves.Counter, Moves.Earthquake, Moves.SkullBash, Moves.RockSlide, Moves.Curse, Moves.Reversal, Moves.ScaryFace, Moves.Magnitude, Moves.Megahorn, Moves.Pursuit, Moves.IronTail, Moves.Crunch, Moves.CrushClaw, Moves.RockBlast, Moves.MetalBurst, Moves.DragonRush, Moves.ThunderFang, Moves.IceFang, Moves.FireFang, Moves.RockClimb, Moves.StoneEdge, Moves.GuardSplit, Moves.SmackDown, Moves.ChipAway, Moves.Bulldoze, Moves.DrillRun, Moves.Rototiller, ]), // Pkmn #111
    new Pokemon(112, "Rhydon", [Types.Rock, Types.Ground, ], Rarity.Uncommon, 42, 2, 0, `Rhydon has a horn that serves as a drill. It is used for destroying rocks and boulders. This Pokémon occasionally rams into streams of magma, but the armor-like hide prevents it from feeling the heat.`, true, false, 130, 120, 105, [Moves.Stomp, Moves.HornAttack, Moves.FuryAttack, Moves.HornDrill, Moves.TakeDown, Moves.TailWhip, Moves.Leer, Moves.Earthquake, Moves.ScaryFace, Moves.Megahorn, Moves.RockBlast, Moves.HammerArm, Moves.StoneEdge, Moves.SmackDown, Moves.ChipAway, Moves.Bulldoze, Moves.DrillRun, ]), // Pkmn #112
    new Pokemon(113, "Chansey", [Types.Normal, ], Rarity.Rare, 1, 1, 0, `Not only are these Pokémon fast runners, they’re also few in number, so anyone who finds one must be lucky indeed.`, false, false, 5, 5, 250, [Moves.Pound, Moves.DoubleSlap, Moves.TakeDown, Moves.DoubleEdge, Moves.TailWhip, Moves.Growl, Moves.Sing, Moves.Counter, Moves.SeismicToss, Moves.Minimize, Moves.DefenseCurl, Moves.LightScreen, Moves.Metronome, Moves.EggBomb, Moves.SoftBoiled, Moves.Substitute, Moves.Endure, Moves.HealBell, Moves.Present, Moves.HelpingHand, Moves.Refresh, Moves.Aromatherapy, Moves.Gravity, Moves.HealingWish, Moves.NaturalGift, Moves.Fling, Moves.MudBomb, Moves.HealPulse, Moves.Bestow, ]), // Pkmn #113
    new Pokemon(114, "Tangela", [Types.Grass, ], Rarity.Common, 1, 1, 0, `Tangela’s vines snap off easily if they are grabbed. This happens without pain, allowing it to make a quick getaway. The lost vines are replaced by newly grown vines the very next day.`, false, false, 55, 115, 65, [Moves.Bind, Moves.Slam, Moves.VineWhip, Moves.Absorb, Moves.MegaDrain, Moves.LeechSeed, Moves.Growth, Moves.PoisonPowder, Moves.StunSpore, Moves.SleepPowder, Moves.Confusion, Moves.Reflect, Moves.Constrict, Moves.Amnesia, Moves.Flail, Moves.GigaDrain, Moves.AncientPower, Moves.NaturePower, Moves.Ingrain, Moves.KnockOff, Moves.Endeavor, Moves.Tickle, Moves.NaturalGift, Moves.WringOut, Moves.PowerSwap, Moves.LeafStorm, Moves.PowerWhip, Moves.RagePowder, Moves.GrassyTerrain, ]), // Pkmn #114
    new Pokemon(115, "Kangaskhan", [Types.Normal, ], Rarity.Rare, 1, 1, 0, `The child in its pouch leaves home after roughly three years. That is the only time the mother is heard to cry wildly.`, false, false, 95, 80, 105, [Moves.CometPunch, Moves.MegaPunch, Moves.Stomp, Moves.DoubleEdge, Moves.TailWhip, Moves.Leer, Moves.Bite, Moves.Disable, Moves.Counter, Moves.Rage, Moves.FocusEnergy, Moves.DizzyPunch, Moves.Substitute, Moves.Reversal, Moves.Foresight, Moves.Outrage, Moves.Endure, Moves.Safeguard, Moves.Crunch, Moves.FakeOut, Moves.Uproar, Moves.FocusPunch, Moves.Endeavor, Moves.CrushClaw, Moves.HammerArm, Moves.TrumpCard, Moves.SuckerPunch, Moves.DoubleHit, Moves.ChipAway, Moves.CircleThrow, ]), // Pkmn #115
    new Pokemon(116, "Horsea", [Types.Water, ], Rarity.Common, 1, 1, 32, `If Horsea senses danger, it will reflexively spray a dense black ink from its mouth and try to escape. This Pokémon swims by cleverly flapping the fin on its back.`, false, false, 40, 70, 30, [Moves.RazorWind, Moves.Leer, Moves.Disable, Moves.WaterGun, Moves.HydroPump, Moves.BubbleBeam, Moves.AuroraBeam, Moves.DragonRage, Moves.Agility, Moves.Smokescreen, Moves.FocusEnergy, Moves.Bubble, Moves.Splash, Moves.Flail, Moves.Octazooka, Moves.Outrage, Moves.DragonBreath, Moves.Twister, Moves.SignalBeam, Moves.MuddyWater, Moves.DragonDance, Moves.WaterPulse, Moves.Brine, Moves.DragonPulse, Moves.ClearSmog, ]), // Pkmn #116
    new Pokemon(117, "Seadra", [Types.Water, ], Rarity.Uncommon, 32, 2, 0, `Seadra generates whirlpools by spinning its body. The whirlpools are strong enough to swallow even fishing boats. This Pokémon weakens prey with these currents, then swallows it whole.`, true, false, 65, 95, 55, [Moves.Leer, Moves.WaterGun, Moves.HydroPump, Moves.BubbleBeam, Moves.Agility, Moves.Smokescreen, Moves.FocusEnergy, Moves.Bubble, Moves.Twister, Moves.DragonDance, Moves.Brine, Moves.DragonPulse, ]), // Pkmn #117
    new Pokemon(118, "Goldeen", [Types.Water, ], Rarity.Common, 1, 1, 33, `Spellbound by the length of its horn and the beauty of its fins, many strange Trainers raise Goldeen and nothing but Goldeen.`, false, false, 67, 60, 45, [Moves.HornAttack, Moves.FuryAttack, Moves.HornDrill, Moves.BodySlam, Moves.TailWhip, Moves.Supersonic, Moves.HydroPump, Moves.Psybeam, Moves.Peck, Moves.Agility, Moves.Haze, Moves.Waterfall, Moves.SkullBash, Moves.Flail, Moves.MudSlap, Moves.SleepTalk, Moves.Megahorn, Moves.MudSport, Moves.SignalBeam, Moves.MudShot, Moves.WaterSport, Moves.WaterPulse, Moves.AquaRing, Moves.AquaTail, Moves.Soak, ]), // Pkmn #118
    new Pokemon(119, "Seaking", [Types.Water, ], Rarity.Uncommon, 33, 2, 0, `Trainers who are crazy for Seaking are divided into horn enthusiasts and fin enthusiasts. The two groups do not get along well.`, false, false, 92, 65, 80, [Moves.HornAttack, Moves.FuryAttack, Moves.HornDrill, Moves.TailWhip, Moves.Supersonic, Moves.Peck, Moves.Agility, Moves.Waterfall, Moves.Flail, Moves.Megahorn, Moves.WaterSport, Moves.WaterPulse, Moves.AquaRing, Moves.PoisonJab, Moves.Soak, ]), // Pkmn #119
    new Pokemon(120, "Staryu", [Types.Water, ], Rarity.Common, 1, 1, 0, `This Pokémon gets nibbled on by Lumineon and others. Thanks to its red core, it regenerates fast, so it’s unconcerned by their snack attacks.`, false, true, 45, 55, 30, [Moves.Tackle, Moves.Supersonic, Moves.WaterGun, Moves.HydroPump, Moves.BubbleBeam, Moves.AuroraBeam, Moves.Psychic, Moves.Recover, Moves.Harden, Moves.Minimize, Moves.ConfuseRay, Moves.Barrier, Moves.LightScreen, Moves.Swift, Moves.Psywave, Moves.RapidSpin, Moves.Camouflage, Moves.CosmicPower, Moves.GyroBall, Moves.Brine, Moves.PowerGem, Moves.ReflectType, ]), // Pkmn #120
    new Pokemon(121, "Starmie", [Types.Psychic, Types.Water, ], Rarity.Common, 30, 2, 0, `Its unusual body shape, reminiscent of abstract art, led local people to spread rumors that this Pokémon may be an invader from outer space.`, false, false, 75, 85, 60, [Moves.Tackle, Moves.WaterGun, Moves.HydroPump, Moves.BubbleBeam, Moves.Recover, Moves.Harden, Moves.ConfuseRay, Moves.Swift, Moves.RapidSpin, Moves.Spotlight, ]), // Pkmn #121
    new Pokemon(122, "Mr Mime", [Types.Fairy, Types.Psychic, ], Rarity.Rare, 0, 1, 0, `Mr. Mime is a master of pantomime. Its gestures and motions convince watchers that something unseeable actually exists. Once the watchers are convinced, the unseeable thing exists as if it were real.`, false, false, 45, 65, 40, [Moves.DoubleSlap, Moves.Psybeam, Moves.Confusion, Moves.Psychic, Moves.Hypnosis, Moves.Meditate, Moves.Mimic, Moves.ConfuseRay, Moves.Barrier, Moves.LightScreen, Moves.Reflect, Moves.Psywave, Moves.Substitute, Moves.IcyWind, Moves.Safeguard, Moves.BatonPass, Moves.Encore, Moves.PsychUp, Moves.FutureSight, Moves.FakeOut, Moves.Trick, Moves.RolePlay, Moves.Recycle, Moves.TeeterDance, Moves.MagicalLeaf, Moves.WakeUpSlap, Moves.Copycat, Moves.PowerSwap, Moves.GuardSwap, Moves.NastyPlot, Moves.WideGuard, Moves.PowerSplit, Moves.MagicRoom, Moves.QuickGuard, Moves.MistyTerrain, ]), // Pkmn #122
    new Pokemon(123, "Scyther", [Types.Flying, Types.Bug, ], Rarity.Rare, 1, 1, 0, `While young, they live together deep in the mountains, training themselves in how to fight with their scythes and move at high speeds.`, true, false, 110, 80, 70, [Moves.RazorWind, Moves.SwordsDance, Moves.WingAttack, Moves.Leer, Moves.Counter, Moves.Agility, Moves.QuickAttack, Moves.DoubleTeam, Moves.LightScreen, Moves.FocusEnergy, Moves.Slash, Moves.Reversal, Moves.Endure, Moves.FalseSwipe, Moves.FuryCutter, Moves.SteelWing, Moves.Safeguard, Moves.BatonPass, Moves.Pursuit, Moves.SilverWind, Moves.Feint, Moves.NightSlash, Moves.AirSlash, Moves.XScissor, Moves.BugBuzz, Moves.VacuumWave, Moves.Defog, Moves.DoubleHit, Moves.QuickGuard, ]), // Pkmn #123
    new Pokemon(124, "Jynx", [Types.Psychic, Types.Ice, ], Rarity.Uncommon, 30, 1, 0, `Jynx walks rhythmically, swaying and shaking its hips as if it were dancing. Its motions are so bouncingly alluring, people seeing it are compelled to shake their hips without giving any thought to what they are doing.`, false, false, 50, 35, 65, [Moves.Pound, Moves.DoubleSlap, Moves.IcePunch, Moves.BodySlam, Moves.Thrash, Moves.Blizzard, Moves.Lick, Moves.LovelyKiss, Moves.PowderSnow, Moves.PerishSong, Moves.MeanLook, Moves.FakeTears, Moves.WakeUpSlap, Moves.WringOut, Moves.Avalanche, Moves.HeartStamp, Moves.DrainingKiss, ]), // Pkmn #124
    new Pokemon(125, "Electabuzz", [Types.Electric, ], Rarity.Rare, 30, 1, 0, `Electricity leaks from it in amounts far greater than the amount of electricity it eats.`, true, false, 83, 57, 65, [Moves.ThunderPunch, Moves.Leer, Moves.LowKick, Moves.ThunderShock, Moves.Thunderbolt, Moves.ThunderWave, Moves.Thunder, Moves.QuickAttack, Moves.Screech, Moves.LightScreen, Moves.Swift, Moves.ShockWave, Moves.Discharge, Moves.ElectroBall, ]), // Pkmn #125
    new Pokemon(126, "Magmar", [Types.Fire, ], Rarity.Uncommon, 30, 1, 0, `When angered, it spouts brilliant fire from all over its body. It doesn’t calm down until its opponent has burned to ash.`, true, false, 95, 57, 65, [Moves.FirePunch, Moves.Leer, Moves.Ember, Moves.Flamethrower, Moves.FireSpin, Moves.Smokescreen, Moves.ConfuseRay, Moves.Smog, Moves.FireBlast, Moves.FeintAttack, Moves.SunnyDay, Moves.LavaPlume, Moves.FlameBurst, Moves.ClearSmog, ]), // Pkmn #126
    new Pokemon(127, "Pinsir", [Types.Bug, ], Rarity.Rare, 1, 1, 0, `One solid blow from its horns is enough to split apart a large tree. Its greatest rival in Alola is Vikavolt.`, false, false, 125, 100, 65, [Moves.ViceGrip, Moves.Guillotine, Moves.SwordsDance, Moves.Bind, Moves.FuryAttack, Moves.Thrash, Moves.Submission, Moves.SeismicToss, Moves.QuickAttack, Moves.Harden, Moves.FocusEnergy, Moves.Slash, Moves.Flail, Moves.FeintAttack, Moves.FalseSwipe, Moves.VitalThrow, Moves.Superpower, Moves.Revenge, Moves.BrickBreak, Moves.Feint, Moves.CloseCombat, Moves.MeFirst, Moves.XScissor, Moves.BugBite, Moves.DoubleHit, Moves.StormThrow, ]), // Pkmn #127
    new Pokemon(128, "Tauros", [Types.Normal, ], Rarity.Uncommon, 1, 1, 0, `Although it’s known to be a fierce Pokémon, Tauros in the Alola region are said to possess a measure of calmness.`, false, false, 100, 95, 75, [Moves.Stomp, Moves.HornAttack, Moves.Tackle, Moves.TakeDown, Moves.Thrash, Moves.TailWhip, Moves.Leer, Moves.Rage, Moves.Rest, Moves.ScaryFace, Moves.Swagger, Moves.Pursuit, Moves.Payback, Moves.GigaImpact, Moves.ZenHeadbutt, Moves.WorkUp, ]), // Pkmn #128
    new Pokemon(129, "Magikarp", [Types.Water, ], Rarity.Uncommon, 1, 1, 20, `Its reckless leaps make it easy pickings for predators. On the bright side, many Pokémon enjoy longer life spans, thanks to Magikarp.`, false, false, 10, 55, 20, [Moves.Tackle, Moves.Splash, Moves.Flail, ]), // Pkmn #129
    new Pokemon(130, "Gyarados", [Types.Flying, Types.Water, ], Rarity.Rare, 20, 2, 0, `There are people who swear that any place Gyarados appears is fated for destruction.`, false, false, 125, 79, 95, [Moves.Tackle, Moves.Thrash, Moves.Leer, Moves.Bite, Moves.HydroPump, Moves.HyperBeam, Moves.DragonRage, Moves.ScaryFace, Moves.Twister, Moves.RainDance, Moves.Crunch, Moves.DragonDance, Moves.AquaTail, Moves.IceFang, Moves.Hurricane, ]), // Pkmn #130
    new Pokemon(131, "Lapras", [Types.Ice, Types.Water, ], Rarity.Rare, 1, 1, 0, `These Pokémon were once near extinction due to poaching. Following protective regulations, there is now an overabundance of them.`, false, false, 85, 80, 130, [Moves.HornDrill, Moves.BodySlam, Moves.Growl, Moves.Sing, Moves.Mist, Moves.WaterGun, Moves.HydroPump, Moves.IceBeam, Moves.AuroraBeam, Moves.Fissure, Moves.ConfuseRay, Moves.Substitute, Moves.Curse, Moves.Foresight, Moves.PerishSong, Moves.SleepTalk, Moves.Safeguard, Moves.RainDance, Moves.AncientPower, Moves.FutureSight, Moves.Whirlpool, Moves.Refresh, Moves.Tickle, Moves.SheerCold, Moves.DragonDance, Moves.WaterPulse, Moves.Brine, Moves.DragonPulse, Moves.Avalanche, Moves.IceShard, Moves.FreezeDry, ]), // Pkmn #131
    new Pokemon(132, "Ditto", [Types.Normal, ], Rarity.Rare, 1, 1, 0, `With its astonishing capacity for metamorphosis, it can get along with anything. It does not get along well with its fellow Ditto.`, false, false, 48, 48, 48, [Moves.Transform, ]), // Pkmn #132
    new Pokemon(133, "Eevee", [Types.Normal, ], Rarity.Common, 1, 1, 0, `Current studies show it can evolve into an incredible eight different species of Pokémon.`, false, true, 55, 50, 55, [Moves.SandAttack, Moves.Tackle, Moves.TakeDown, Moves.DoubleEdge, Moves.TailWhip, Moves.Bite, Moves.Growl, Moves.QuickAttack, Moves.FocusEnergy, Moves.Swift, Moves.Curse, Moves.Flail, Moves.Detect, Moves.Endure, Moves.Charm, Moves.BatonPass, Moves.HelpingHand, Moves.Wish, Moves.Yawn, Moves.Refresh, Moves.FakeTears, Moves.Tickle, Moves.Covet, Moves.NaturalGift, Moves.TrumpCard, Moves.LastResort, Moves.Captivate, Moves.Synchronoise, Moves.StoredPower, Moves.BabyDollEyes, ]), // Pkmn #133
    new Pokemon(134, "Vaporeon", [Types.Water, ], Rarity.Rare, 30, 2, 0, `Blending in with the water and erasing all signs of its presence, it patiently waits for its prey, fish Pokémon.`, false, false, 65, 60, 130, [Moves.SandAttack, Moves.Tackle, Moves.TailWhip, Moves.Bite, Moves.Mist, Moves.WaterGun, Moves.HydroPump, Moves.AuroraBeam, Moves.QuickAttack, Moves.Haze, Moves.AcidArmor, Moves.HelpingHand, Moves.MuddyWater, Moves.WaterPulse, Moves.LastResort, Moves.AquaRing, Moves.BabyDollEyes, ]), // Pkmn #134
    new Pokemon(135, "Jolteon", [Types.Electric, ], Rarity.Rare, 30, 2, 0, `When its fur stands on end, that’s a sign it’s about to give off a jolt of electricity. Take care, as sometimes lightning strikes next to it, too.`, false, false, 65, 60, 65, [Moves.DoubleKick, Moves.SandAttack, Moves.Tackle, Moves.TailWhip, Moves.PinMissile, Moves.ThunderShock, Moves.ThunderWave, Moves.Thunder, Moves.Agility, Moves.QuickAttack, Moves.HelpingHand, Moves.LastResort, Moves.ThunderFang, Moves.Discharge, Moves.BabyDollEyes, ]), // Pkmn #135
    new Pokemon(136, "Flareon", [Types.Fire, ], Rarity.Rare, 30, 2, 0, `Its average body temperature is between 1,300 and 1,500 degrees Fahrenheit. In its internal flame sac, temperatures reach 3,000 degrees.`, false, false, 130, 60, 65, [Moves.SandAttack, Moves.Tackle, Moves.TailWhip, Moves.Leer, Moves.Bite, Moves.Ember, Moves.Flamethrower, Moves.FireSpin, Moves.QuickAttack, Moves.Rage, Moves.Smog, Moves.FireBlast, Moves.ScaryFace, Moves.HelpingHand, Moves.LastResort, Moves.FlareBlitz, Moves.FireFang, Moves.LavaPlume, Moves.BabyDollEyes, ]), // Pkmn #136
    new Pokemon(137, "Porygon", [Types.Normal, ], Rarity.Uncommon, 1, 1, 0, `It can convert its body into digital data, which enables it to enter cyberspace.`, true, false, 60, 70, 65, [Moves.Tackle, Moves.Psybeam, Moves.Agility, Moves.Recover, Moves.Sharpen, Moves.Conversion, Moves.TriAttack, Moves.Conversion2, Moves.ZapCannon, Moves.LockOn, Moves.MagicCoat, Moves.Recycle, Moves.SignalBeam, Moves.MagnetRise, Moves.Discharge, ]), // Pkmn #137
    new Pokemon(138, "Omanyte", [Types.Water, Types.Rock, ], Rarity.Uncommon, 1, 2, 40, `Omanyte is one of the ancient and long-since-extinct Pokémon that have been regenerated from fossils by people. If attacked by an enemy, it withdraws itself inside its hard shell.`, false, false, 40, 100, 35, [Moves.Slam, Moves.HornAttack, Moves.Leer, Moves.Bite, Moves.Supersonic, Moves.WaterGun, Moves.HydroPump, Moves.BubbleBeam, Moves.AuroraBeam, Moves.Withdraw, Moves.Haze, Moves.Bide, Moves.SpikeCannon, Moves.Constrict, Moves.RockSlide, Moves.Protect, Moves.Spikes, Moves.Rollout, Moves.AncientPower, Moves.Whirlpool, Moves.KnockOff, Moves.Tickle, Moves.MuddyWater, Moves.MudShot, Moves.RockBlast, Moves.WaterPulse, Moves.Brine, Moves.WringOut, Moves.ToxicSpikes, Moves.ShellSmash, Moves.ReflectType, ]), // Pkmn #138
    new Pokemon(139, "Omastar", [Types.Water, Types.Rock, ], Rarity.Uncommon, 40, 3, 0, `Omastar uses its tentacles to capture its prey. It is believed to have become extinct because its shell grew too large and heavy, causing its movements to become too slow and ponderous.`, false, false, 60, 125, 70, [Moves.HornAttack, Moves.Leer, Moves.Bite, Moves.WaterGun, Moves.HydroPump, Moves.Withdraw, Moves.SpikeCannon, Moves.Constrict, Moves.Protect, Moves.Rollout, Moves.AncientPower, Moves.Tickle, Moves.MudShot, Moves.RockBlast, Moves.Brine, Moves.ShellSmash, ]), // Pkmn #139
    new Pokemon(140, "Kabuto", [Types.Water, Types.Rock, ], Rarity.Uncommon, 1, 2, 40, `Kabuto is a Pokémon that has been regenerated from a fossil. However, in extremely rare cases, living examples have been discovered. The Pokémon has not changed at all for 300 million years.`, false, false, 80, 90, 30, [Moves.Scratch, Moves.SandAttack, Moves.TakeDown, Moves.Leer, Moves.HydroPump, Moves.BubbleBeam, Moves.AuroraBeam, Moves.Absorb, Moves.MegaDrain, Moves.Dig, Moves.Screech, Moves.Harden, Moves.ConfuseRay, Moves.Slash, Moves.Flail, Moves.Foresight, Moves.IcyWind, Moves.GigaDrain, Moves.Endure, Moves.RapidSpin, Moves.AncientPower, Moves.KnockOff, Moves.MetalSound, Moves.MudShot, Moves.WringOut, Moves.AquaJet, ]), // Pkmn #140
    new Pokemon(141, "Kabutops", [Types.Water, Types.Rock, ], Rarity.Rare, 40, 3, 0, `Kabutops swam underwater to hunt for its prey in ancient times. The Pokémon was apparently evolving from being a water dweller to living on land as evident from the beginnings of change in its gills and legs.`, false, false, 115, 105, 60, [Moves.Scratch, Moves.SandAttack, Moves.Leer, Moves.HydroPump, Moves.Absorb, Moves.MegaDrain, Moves.Harden, Moves.Slash, Moves.Endure, Moves.FuryCutter, Moves.AncientPower, Moves.MetalSound, Moves.MudShot, Moves.Feint, Moves.WringOut, Moves.NightSlash, Moves.AquaJet, ]), // Pkmn #141
    new Pokemon(142, "Aerodactyl", [Types.Flying, Types.Rock, ], Rarity.Rare, 1, 2, 0, `In ancient times, it ruled the skies. A widely accepted theory is that it went extinct due to a large meteor impact.`, false, false, 105, 65, 80, [Moves.WingAttack, Moves.Whirlwind, Moves.TakeDown, Moves.Bite, Moves.Roar, Moves.Supersonic, Moves.HyperBeam, Moves.Agility, Moves.RockSlide, Moves.Curse, Moves.ScaryFace, Moves.Foresight, Moves.SteelWing, Moves.DragonBreath, Moves.Pursuit, Moves.Crunch, Moves.AncientPower, Moves.Roost, Moves.Tailwind, Moves.Assurance, Moves.GigaImpact, Moves.ThunderFang, Moves.IceFang, Moves.FireFang, Moves.IronHead, Moves.WideGuard, Moves.SkyDrop, ]), // Pkmn #142
    new Pokemon(143, "Snorlax", [Types.Normal, ], Rarity.Rare, 1, 1, 0, `It eats nearly 900 pounds of food every day. It starts nodding off while eating—and continues to eat even while it’s asleep.`, false, false, 110, 65, 160, [Moves.Whirlwind, Moves.Headbutt, Moves.Tackle, Moves.BodySlam, Moves.DoubleEdge, Moves.HyperBeam, Moves.Counter, Moves.Fissure, Moves.Harden, Moves.DefenseCurl, Moves.Lick, Moves.Amnesia, Moves.Rest, Moves.Substitute, Moves.Snore, Moves.Curse, Moves.BellyDrum, Moves.Charm, Moves.Rollout, Moves.SleepTalk, Moves.Pursuit, Moves.Crunch, Moves.Yawn, Moves.Block, Moves.Covet, Moves.NaturalGift, Moves.GigaImpact, Moves.HeavySlam, Moves.AfterYou, Moves.ChipAway, Moves.Belch, Moves.HighHorsepower, ]), // Pkmn #143
    new Pokemon(144, "Articuno", [Types.Ice, Types.Flying, ], Rarity.Legendary, 80, 1, 0, `Articuno is a legendary bird Pokémon that can control ice. The flapping of its wings chills the air. As a result, it is said that when this Pokémon flies, snow will fall.`, false, false, 85, 100, 90, [Moves.Gust, Moves.Mist, Moves.IceBeam, Moves.Blizzard, Moves.Peck, Moves.Agility, Moves.Reflect, Moves.MindReader, Moves.PowderSnow, Moves.AncientPower, Moves.Hail, Moves.SheerCold, Moves.Roost, Moves.Tailwind, Moves.IceShard, Moves.Hurricane, Moves.FreezeDry, ]), // Pkmn #144
    new Pokemon(145, "Zapdos", [Types.Electric, Types.Flying, ], Rarity.Legendary, 80, 1, 0, `Zapdos is a legendary bird Pokémon that has the ability to control electricity. It usually lives in thunderclouds. The Pokémon gains power if it is stricken by lightning bolts.`, false, false, 90, 85, 90, [Moves.Peck, Moves.DrillPeck, Moves.ThunderShock, Moves.ThunderWave, Moves.Thunder, Moves.Agility, Moves.LightScreen, Moves.ZapCannon, Moves.Detect, Moves.RainDance, Moves.AncientPower, Moves.Charge, Moves.Roost, Moves.Pluck, Moves.Discharge, Moves.MagneticFlux, ]), // Pkmn #145
    new Pokemon(146, "Moltres", [Types.Fire, Types.Flying, ], Rarity.Legendary, 80, 1, 0, `Moltres is a legendary bird Pokémon that has the ability to control fire. If this Pokémon is injured, it is said to dip its body in the molten magma of a volcano to burn and heal itself.`, false, false, 100, 90, 90, [Moves.WingAttack, Moves.Leer, Moves.Ember, Moves.Flamethrower, Moves.Peck, Moves.SolarBeam, Moves.FireSpin, Moves.Agility, Moves.SkyAttack, Moves.Endure, Moves.Safeguard, Moves.SunnyDay, Moves.AncientPower, Moves.HeatWave, Moves.Roost, Moves.AirSlash, Moves.Hurricane, Moves.BurnUp, ]), // Pkmn #146
    new Pokemon(147, "Dratini", [Types.Dragon, ], Rarity.Uncommon, 1, 1, 30, `After a 10-hour struggle, a fisherman was able to pull one up and confirm its existence.`, false, false, 64, 45, 41, [Moves.Slam, Moves.Wrap, Moves.Leer, Moves.Supersonic, Moves.Mist, Moves.HyperBeam, Moves.DragonRage, Moves.ThunderWave, Moves.Agility, Moves.LightScreen, Moves.Haze, Moves.Outrage, Moves.Safeguard, Moves.DragonBreath, Moves.IronTail, Moves.Twister, Moves.ExtremeSpeed, Moves.DragonDance, Moves.WaterPulse, Moves.AquaTail, Moves.DragonPulse, Moves.DragonRush, Moves.AquaJet, Moves.DragonTail, ]), // Pkmn #147
    new Pokemon(148, "Dragonair", [Types.Dragon, ], Rarity.Rare, 30, 2, 55, `From time immemorial, it has been venerated by agricultural peoples as an entity able to control the weather.`, false, false, 84, 65, 61, [Moves.Slam, Moves.Wrap, Moves.Leer, Moves.HyperBeam, Moves.DragonRage, Moves.ThunderWave, Moves.Agility, Moves.Outrage, Moves.Safeguard, Moves.Twister, Moves.DragonDance, Moves.AquaTail, Moves.DragonRush, Moves.DragonTail, ]), // Pkmn #148
    new Pokemon(149, "Dragonite", [Types.Flying, Types.Dragon, ], Rarity.Rare, 55, 3, 0, `Incur the wrath of this normally calm Pokémon at your peril, because it will smash everything to smithereens before it’s satisfied.`, false, false, 134, 95, 91, [Moves.FirePunch, Moves.ThunderPunch, Moves.WingAttack, Moves.Slam, Moves.Wrap, Moves.Leer, Moves.HyperBeam, Moves.DragonRage, Moves.ThunderWave, Moves.Agility, Moves.Outrage, Moves.Safeguard, Moves.Twister, Moves.DragonDance, Moves.Roost, Moves.AquaTail, Moves.DragonRush, Moves.DragonTail, Moves.Hurricane, ]), // Pkmn #149
    new Pokemon(150, "Mewtwo", [Types.Psychic, ], Rarity.Legendary, 80, 1, 0, `Mewtwo is a Pokémon that was created by genetic manipulation. However, even though the scientific power of humans created this Pokémon’s body, they failed to endow Mewtwo with a compassionate heart.`, false, false, 110, 90, 106, [Moves.Disable, Moves.Mist, Moves.Confusion, Moves.Psychic, Moves.Recover, Moves.Barrier, Moves.Swift, Moves.Amnesia, Moves.Psywave, Moves.Safeguard, Moves.PsychUp, Moves.FutureSight, Moves.MiracleEye, Moves.MeFirst, Moves.PowerSwap, Moves.GuardSwap, Moves.AuraSphere, Moves.PsychoCut, Moves.Psystrike, Moves.LaserFocus, ]), // Pkmn #150
    new Pokemon(151, "Mew", [Types.Psychic, ], Rarity.Unobtainable, 80, 1, 0, `Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.`, false, false, 100, 100, 100, [Moves.Pound, Moves.MegaPunch, Moves.Psychic, Moves.Barrier, Moves.Metronome, Moves.Amnesia, Moves.Transform, Moves.BatonPass, Moves.AncientPower, Moves.MeFirst, Moves.AuraSphere, Moves.NastyPlot, Moves.ReflectType, ]), // Pkmn #151
];

export { InternPokemon as Pokemons };
